# golangci-lint configuration for Hector  
run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

linters-settings:
  goimports:
    local-prefixes: github.com/kadirpekel/hector
  misspell:
    locale: US

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  
  # Exclude known false positives and non-critical suggestions
  exclude:
    - 'S1016.*should convert.*instead of using struct literal'  # gosimple: explicit is fine
    - 'File is not properly formatted'  # goimports false positives
