global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'hector-monitor'
    environment: 'development'

# Alerting configuration (optional)
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Load rules once and periodically evaluate them
rule_files:
  # - "alert_rules.yml"
  # - "recording_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Hector metrics endpoint
  - job_name: 'hector'
    scrape_interval: 10s
    scrape_timeout: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:8081']
        labels:
          service: 'hector'
          environment: 'development'
