// AG-UI Protocol Definition
// Implements the Agent User Interaction Protocol (AG-UI)
// https://docs.ag-ui.com/

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: agui.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AGUIEventType defines the 16 standardized AG-UI event types
type AGUIEventType int32

const (
	AGUIEventType_AGUI_EVENT_TYPE_UNSPECIFIED AGUIEventType = 0
	// Message Events (3)
	AGUIEventType_AGUI_EVENT_TYPE_MESSAGE_START AGUIEventType = 1
	AGUIEventType_AGUI_EVENT_TYPE_MESSAGE_DELTA AGUIEventType = 2
	AGUIEventType_AGUI_EVENT_TYPE_MESSAGE_STOP  AGUIEventType = 3
	// Content Block Events (3)
	AGUIEventType_AGUI_EVENT_TYPE_CONTENT_BLOCK_START AGUIEventType = 4
	AGUIEventType_AGUI_EVENT_TYPE_CONTENT_BLOCK_DELTA AGUIEventType = 5
	AGUIEventType_AGUI_EVENT_TYPE_CONTENT_BLOCK_STOP  AGUIEventType = 6
	// Tool Call Events (3)
	AGUIEventType_AGUI_EVENT_TYPE_TOOL_CALL_START AGUIEventType = 7
	AGUIEventType_AGUI_EVENT_TYPE_TOOL_CALL_DELTA AGUIEventType = 8
	AGUIEventType_AGUI_EVENT_TYPE_TOOL_CALL_STOP  AGUIEventType = 9
	// Thinking Events (3)
	AGUIEventType_AGUI_EVENT_TYPE_THINKING_START AGUIEventType = 10
	AGUIEventType_AGUI_EVENT_TYPE_THINKING_DELTA AGUIEventType = 11
	AGUIEventType_AGUI_EVENT_TYPE_THINKING_STOP  AGUIEventType = 12
	// Task Events (4)
	AGUIEventType_AGUI_EVENT_TYPE_TASK_START    AGUIEventType = 13
	AGUIEventType_AGUI_EVENT_TYPE_TASK_UPDATE   AGUIEventType = 14
	AGUIEventType_AGUI_EVENT_TYPE_TASK_COMPLETE AGUIEventType = 15
	AGUIEventType_AGUI_EVENT_TYPE_TASK_ERROR    AGUIEventType = 16
)

// Enum value maps for AGUIEventType.
var (
	AGUIEventType_name = map[int32]string{
		0:  "AGUI_EVENT_TYPE_UNSPECIFIED",
		1:  "AGUI_EVENT_TYPE_MESSAGE_START",
		2:  "AGUI_EVENT_TYPE_MESSAGE_DELTA",
		3:  "AGUI_EVENT_TYPE_MESSAGE_STOP",
		4:  "AGUI_EVENT_TYPE_CONTENT_BLOCK_START",
		5:  "AGUI_EVENT_TYPE_CONTENT_BLOCK_DELTA",
		6:  "AGUI_EVENT_TYPE_CONTENT_BLOCK_STOP",
		7:  "AGUI_EVENT_TYPE_TOOL_CALL_START",
		8:  "AGUI_EVENT_TYPE_TOOL_CALL_DELTA",
		9:  "AGUI_EVENT_TYPE_TOOL_CALL_STOP",
		10: "AGUI_EVENT_TYPE_THINKING_START",
		11: "AGUI_EVENT_TYPE_THINKING_DELTA",
		12: "AGUI_EVENT_TYPE_THINKING_STOP",
		13: "AGUI_EVENT_TYPE_TASK_START",
		14: "AGUI_EVENT_TYPE_TASK_UPDATE",
		15: "AGUI_EVENT_TYPE_TASK_COMPLETE",
		16: "AGUI_EVENT_TYPE_TASK_ERROR",
	}
	AGUIEventType_value = map[string]int32{
		"AGUI_EVENT_TYPE_UNSPECIFIED":         0,
		"AGUI_EVENT_TYPE_MESSAGE_START":       1,
		"AGUI_EVENT_TYPE_MESSAGE_DELTA":       2,
		"AGUI_EVENT_TYPE_MESSAGE_STOP":        3,
		"AGUI_EVENT_TYPE_CONTENT_BLOCK_START": 4,
		"AGUI_EVENT_TYPE_CONTENT_BLOCK_DELTA": 5,
		"AGUI_EVENT_TYPE_CONTENT_BLOCK_STOP":  6,
		"AGUI_EVENT_TYPE_TOOL_CALL_START":     7,
		"AGUI_EVENT_TYPE_TOOL_CALL_DELTA":     8,
		"AGUI_EVENT_TYPE_TOOL_CALL_STOP":      9,
		"AGUI_EVENT_TYPE_THINKING_START":      10,
		"AGUI_EVENT_TYPE_THINKING_DELTA":      11,
		"AGUI_EVENT_TYPE_THINKING_STOP":       12,
		"AGUI_EVENT_TYPE_TASK_START":          13,
		"AGUI_EVENT_TYPE_TASK_UPDATE":         14,
		"AGUI_EVENT_TYPE_TASK_COMPLETE":       15,
		"AGUI_EVENT_TYPE_TASK_ERROR":          16,
	}
)

func (x AGUIEventType) Enum() *AGUIEventType {
	p := new(AGUIEventType)
	*p = x
	return p
}

func (x AGUIEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AGUIEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agui_proto_enumTypes[0].Descriptor()
}

func (AGUIEventType) Type() protoreflect.EnumType {
	return &file_agui_proto_enumTypes[0]
}

func (x AGUIEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AGUIEventType.Descriptor instead.
func (AGUIEventType) EnumDescriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{0}
}

// AGUIEvent is the root event structure for AG-UI protocol
type AGUIEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique event identifier
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event type
	Type AGUIEventType `protobuf:"varint,2,opt,name=type,proto3,enum=agui.v1.AGUIEventType" json:"type,omitempty"`
	// Timestamp when event was created
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Event payload (one of the specific event types)
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*AGUIEvent_MessageStart
	//	*AGUIEvent_MessageDelta
	//	*AGUIEvent_MessageStop
	//	*AGUIEvent_ContentBlockStart
	//	*AGUIEvent_ContentBlockDelta
	//	*AGUIEvent_ContentBlockStop
	//	*AGUIEvent_ToolCallStart
	//	*AGUIEvent_ToolCallDelta
	//	*AGUIEvent_ToolCallStop
	//	*AGUIEvent_ThinkingStart
	//	*AGUIEvent_ThinkingDelta
	//	*AGUIEvent_ThinkingStop
	//	*AGUIEvent_TaskStart
	//	*AGUIEvent_TaskUpdate
	//	*AGUIEvent_TaskComplete
	//	*AGUIEvent_TaskError
	Payload isAGUIEvent_Payload `protobuf_oneof:"payload"`
	// Optional metadata for extensibility
	Metadata      *structpb.Struct `protobuf:"bytes,100,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AGUIEvent) Reset() {
	*x = AGUIEvent{}
	mi := &file_agui_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AGUIEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AGUIEvent) ProtoMessage() {}

func (x *AGUIEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AGUIEvent.ProtoReflect.Descriptor instead.
func (*AGUIEvent) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{0}
}

func (x *AGUIEvent) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *AGUIEvent) GetType() AGUIEventType {
	if x != nil {
		return x.Type
	}
	return AGUIEventType_AGUI_EVENT_TYPE_UNSPECIFIED
}

func (x *AGUIEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AGUIEvent) GetPayload() isAGUIEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AGUIEvent) GetMessageStart() *MessageStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_MessageStart); ok {
			return x.MessageStart
		}
	}
	return nil
}

func (x *AGUIEvent) GetMessageDelta() *MessageDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_MessageDelta); ok {
			return x.MessageDelta
		}
	}
	return nil
}

func (x *AGUIEvent) GetMessageStop() *MessageStopPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_MessageStop); ok {
			return x.MessageStop
		}
	}
	return nil
}

func (x *AGUIEvent) GetContentBlockStart() *ContentBlockStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ContentBlockStart); ok {
			return x.ContentBlockStart
		}
	}
	return nil
}

func (x *AGUIEvent) GetContentBlockDelta() *ContentBlockDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ContentBlockDelta); ok {
			return x.ContentBlockDelta
		}
	}
	return nil
}

func (x *AGUIEvent) GetContentBlockStop() *ContentBlockStopPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ContentBlockStop); ok {
			return x.ContentBlockStop
		}
	}
	return nil
}

func (x *AGUIEvent) GetToolCallStart() *ToolCallStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ToolCallStart); ok {
			return x.ToolCallStart
		}
	}
	return nil
}

func (x *AGUIEvent) GetToolCallDelta() *ToolCallDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ToolCallDelta); ok {
			return x.ToolCallDelta
		}
	}
	return nil
}

func (x *AGUIEvent) GetToolCallStop() *ToolCallStopPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ToolCallStop); ok {
			return x.ToolCallStop
		}
	}
	return nil
}

func (x *AGUIEvent) GetThinkingStart() *ThinkingStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ThinkingStart); ok {
			return x.ThinkingStart
		}
	}
	return nil
}

func (x *AGUIEvent) GetThinkingDelta() *ThinkingDeltaPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return nil
}

func (x *AGUIEvent) GetThinkingStop() *ThinkingStopPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_ThinkingStop); ok {
			return x.ThinkingStop
		}
	}
	return nil
}

func (x *AGUIEvent) GetTaskStart() *TaskStartPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_TaskStart); ok {
			return x.TaskStart
		}
	}
	return nil
}

func (x *AGUIEvent) GetTaskUpdate() *TaskUpdatePayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_TaskUpdate); ok {
			return x.TaskUpdate
		}
	}
	return nil
}

func (x *AGUIEvent) GetTaskComplete() *TaskCompletePayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_TaskComplete); ok {
			return x.TaskComplete
		}
	}
	return nil
}

func (x *AGUIEvent) GetTaskError() *TaskErrorPayload {
	if x != nil {
		if x, ok := x.Payload.(*AGUIEvent_TaskError); ok {
			return x.TaskError
		}
	}
	return nil
}

func (x *AGUIEvent) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isAGUIEvent_Payload interface {
	isAGUIEvent_Payload()
}

type AGUIEvent_MessageStart struct {
	MessageStart *MessageStartPayload `protobuf:"bytes,10,opt,name=message_start,json=messageStart,proto3,oneof"`
}

type AGUIEvent_MessageDelta struct {
	MessageDelta *MessageDeltaPayload `protobuf:"bytes,11,opt,name=message_delta,json=messageDelta,proto3,oneof"`
}

type AGUIEvent_MessageStop struct {
	MessageStop *MessageStopPayload `protobuf:"bytes,12,opt,name=message_stop,json=messageStop,proto3,oneof"`
}

type AGUIEvent_ContentBlockStart struct {
	ContentBlockStart *ContentBlockStartPayload `protobuf:"bytes,20,opt,name=content_block_start,json=contentBlockStart,proto3,oneof"`
}

type AGUIEvent_ContentBlockDelta struct {
	ContentBlockDelta *ContentBlockDeltaPayload `protobuf:"bytes,21,opt,name=content_block_delta,json=contentBlockDelta,proto3,oneof"`
}

type AGUIEvent_ContentBlockStop struct {
	ContentBlockStop *ContentBlockStopPayload `protobuf:"bytes,22,opt,name=content_block_stop,json=contentBlockStop,proto3,oneof"`
}

type AGUIEvent_ToolCallStart struct {
	ToolCallStart *ToolCallStartPayload `protobuf:"bytes,30,opt,name=tool_call_start,json=toolCallStart,proto3,oneof"`
}

type AGUIEvent_ToolCallDelta struct {
	ToolCallDelta *ToolCallDeltaPayload `protobuf:"bytes,31,opt,name=tool_call_delta,json=toolCallDelta,proto3,oneof"`
}

type AGUIEvent_ToolCallStop struct {
	ToolCallStop *ToolCallStopPayload `protobuf:"bytes,32,opt,name=tool_call_stop,json=toolCallStop,proto3,oneof"`
}

type AGUIEvent_ThinkingStart struct {
	ThinkingStart *ThinkingStartPayload `protobuf:"bytes,40,opt,name=thinking_start,json=thinkingStart,proto3,oneof"`
}

type AGUIEvent_ThinkingDelta struct {
	ThinkingDelta *ThinkingDeltaPayload `protobuf:"bytes,41,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type AGUIEvent_ThinkingStop struct {
	ThinkingStop *ThinkingStopPayload `protobuf:"bytes,42,opt,name=thinking_stop,json=thinkingStop,proto3,oneof"`
}

type AGUIEvent_TaskStart struct {
	TaskStart *TaskStartPayload `protobuf:"bytes,50,opt,name=task_start,json=taskStart,proto3,oneof"`
}

type AGUIEvent_TaskUpdate struct {
	TaskUpdate *TaskUpdatePayload `protobuf:"bytes,51,opt,name=task_update,json=taskUpdate,proto3,oneof"`
}

type AGUIEvent_TaskComplete struct {
	TaskComplete *TaskCompletePayload `protobuf:"bytes,52,opt,name=task_complete,json=taskComplete,proto3,oneof"`
}

type AGUIEvent_TaskError struct {
	TaskError *TaskErrorPayload `protobuf:"bytes,53,opt,name=task_error,json=taskError,proto3,oneof"`
}

func (*AGUIEvent_MessageStart) isAGUIEvent_Payload() {}

func (*AGUIEvent_MessageDelta) isAGUIEvent_Payload() {}

func (*AGUIEvent_MessageStop) isAGUIEvent_Payload() {}

func (*AGUIEvent_ContentBlockStart) isAGUIEvent_Payload() {}

func (*AGUIEvent_ContentBlockDelta) isAGUIEvent_Payload() {}

func (*AGUIEvent_ContentBlockStop) isAGUIEvent_Payload() {}

func (*AGUIEvent_ToolCallStart) isAGUIEvent_Payload() {}

func (*AGUIEvent_ToolCallDelta) isAGUIEvent_Payload() {}

func (*AGUIEvent_ToolCallStop) isAGUIEvent_Payload() {}

func (*AGUIEvent_ThinkingStart) isAGUIEvent_Payload() {}

func (*AGUIEvent_ThinkingDelta) isAGUIEvent_Payload() {}

func (*AGUIEvent_ThinkingStop) isAGUIEvent_Payload() {}

func (*AGUIEvent_TaskStart) isAGUIEvent_Payload() {}

func (*AGUIEvent_TaskUpdate) isAGUIEvent_Payload() {}

func (*AGUIEvent_TaskComplete) isAGUIEvent_Payload() {}

func (*AGUIEvent_TaskError) isAGUIEvent_Payload() {}

// MessageStartPayload signals the beginning of a message
type MessageStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,3,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"` // "user" | "agent" | "system"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStartPayload) Reset() {
	*x = MessageStartPayload{}
	mi := &file_agui_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStartPayload) ProtoMessage() {}

func (x *MessageStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStartPayload.ProtoReflect.Descriptor instead.
func (*MessageStartPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{1}
}

func (x *MessageStartPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageStartPayload) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *MessageStartPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *MessageStartPayload) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

// MessageDeltaPayload provides incremental message content
type MessageDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"` // Incremental text content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeltaPayload) Reset() {
	*x = MessageDeltaPayload{}
	mi := &file_agui_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeltaPayload) ProtoMessage() {}

func (x *MessageDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeltaPayload.ProtoReflect.Descriptor instead.
func (*MessageDeltaPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{2}
}

func (x *MessageDeltaPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

// MessageStopPayload signals the end of a message
type MessageStopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStopPayload) Reset() {
	*x = MessageStopPayload{}
	mi := &file_agui_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStopPayload) ProtoMessage() {}

func (x *MessageStopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStopPayload.ProtoReflect.Descriptor instead.
func (*MessageStopPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{3}
}

func (x *MessageStopPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// ContentBlockStartPayload signals the start of a content block
type ContentBlockStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	BlockType     string                 `protobuf:"bytes,2,opt,name=block_type,json=blockType,proto3" json:"block_type,omitempty"` // "text" | "image" | "code" | "data"
	Index         int32                  `protobuf:"varint,3,opt,name=index,proto3" json:"index,omitempty"`                         // Index in message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStartPayload) Reset() {
	*x = ContentBlockStartPayload{}
	mi := &file_agui_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStartPayload) ProtoMessage() {}

func (x *ContentBlockStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStartPayload.ProtoReflect.Descriptor instead.
func (*ContentBlockStartPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{4}
}

func (x *ContentBlockStartPayload) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ContentBlockStartPayload) GetBlockType() string {
	if x != nil {
		return x.BlockType
	}
	return ""
}

func (x *ContentBlockStartPayload) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// ContentBlockDeltaPayload provides incremental content updates
type ContentBlockDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"` // Incremental content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockDeltaPayload) Reset() {
	*x = ContentBlockDeltaPayload{}
	mi := &file_agui_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockDeltaPayload) ProtoMessage() {}

func (x *ContentBlockDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockDeltaPayload.ProtoReflect.Descriptor instead.
func (*ContentBlockDeltaPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{5}
}

func (x *ContentBlockDeltaPayload) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *ContentBlockDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

// ContentBlockStopPayload signals the end of a content block
type ContentBlockStopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       string                 `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStopPayload) Reset() {
	*x = ContentBlockStopPayload{}
	mi := &file_agui_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStopPayload) ProtoMessage() {}

func (x *ContentBlockStopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStopPayload.ProtoReflect.Descriptor instead.
func (*ContentBlockStopPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{6}
}

func (x *ContentBlockStopPayload) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

// ToolCallStartPayload signals the start of a tool invocation
type ToolCallStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Input         *structpb.Struct       `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"` // Tool input parameters
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStartPayload) Reset() {
	*x = ToolCallStartPayload{}
	mi := &file_agui_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStartPayload) ProtoMessage() {}

func (x *ToolCallStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStartPayload.ProtoReflect.Descriptor instead.
func (*ToolCallStartPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{7}
}

func (x *ToolCallStartPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallStartPayload) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ToolCallStartPayload) GetInput() *structpb.Struct {
	if x != nil {
		return x.Input
	}
	return nil
}

// ToolCallDeltaPayload provides incremental tool call updates (e.g., partial JSON)
type ToolCallDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	PartialInput  string                 `protobuf:"bytes,2,opt,name=partial_input,json=partialInput,proto3" json:"partial_input,omitempty"` // Partial JSON input (streaming)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallDeltaPayload) Reset() {
	*x = ToolCallDeltaPayload{}
	mi := &file_agui_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallDeltaPayload) ProtoMessage() {}

func (x *ToolCallDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallDeltaPayload.ProtoReflect.Descriptor instead.
func (*ToolCallDeltaPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{8}
}

func (x *ToolCallDeltaPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallDeltaPayload) GetPartialInput() string {
	if x != nil {
		return x.PartialInput
	}
	return ""
}

// ToolCallStopPayload signals the end of a tool call
type ToolCallStopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolCallId    string                 `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	FinalInput    *structpb.Struct       `protobuf:"bytes,2,opt,name=final_input,json=finalInput,proto3" json:"final_input,omitempty"` // Complete tool input
	Result        string                 `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`                           // Tool execution result
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                             // Error message if failed
	IsError       bool                   `protobuf:"varint,5,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`         // Whether execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallStopPayload) Reset() {
	*x = ToolCallStopPayload{}
	mi := &file_agui_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallStopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallStopPayload) ProtoMessage() {}

func (x *ToolCallStopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallStopPayload.ProtoReflect.Descriptor instead.
func (*ToolCallStopPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{9}
}

func (x *ToolCallStopPayload) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolCallStopPayload) GetFinalInput() *structpb.Struct {
	if x != nil {
		return x.FinalInput
	}
	return nil
}

func (x *ToolCallStopPayload) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ToolCallStopPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ToolCallStopPayload) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// ThinkingStartPayload signals the start of agent reasoning
type ThinkingStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThinkingId    string                 `protobuf:"bytes,1,opt,name=thinking_id,json=thinkingId,proto3" json:"thinking_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"` // Optional title/description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingStartPayload) Reset() {
	*x = ThinkingStartPayload{}
	mi := &file_agui_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingStartPayload) ProtoMessage() {}

func (x *ThinkingStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingStartPayload.ProtoReflect.Descriptor instead.
func (*ThinkingStartPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{10}
}

func (x *ThinkingStartPayload) GetThinkingId() string {
	if x != nil {
		return x.ThinkingId
	}
	return ""
}

func (x *ThinkingStartPayload) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// ThinkingDeltaPayload provides incremental thinking/reasoning content
type ThinkingDeltaPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThinkingId    string                 `protobuf:"bytes,1,opt,name=thinking_id,json=thinkingId,proto3" json:"thinking_id,omitempty"`
	Delta         string                 `protobuf:"bytes,2,opt,name=delta,proto3" json:"delta,omitempty"` // Incremental reasoning text
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingDeltaPayload) Reset() {
	*x = ThinkingDeltaPayload{}
	mi := &file_agui_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingDeltaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingDeltaPayload) ProtoMessage() {}

func (x *ThinkingDeltaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingDeltaPayload.ProtoReflect.Descriptor instead.
func (*ThinkingDeltaPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{11}
}

func (x *ThinkingDeltaPayload) GetThinkingId() string {
	if x != nil {
		return x.ThinkingId
	}
	return ""
}

func (x *ThinkingDeltaPayload) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

// ThinkingStopPayload signals the end of thinking
type ThinkingStopPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThinkingId    string                 `protobuf:"bytes,1,opt,name=thinking_id,json=thinkingId,proto3" json:"thinking_id,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // Optional integrity signature (Anthropic-style)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingStopPayload) Reset() {
	*x = ThinkingStopPayload{}
	mi := &file_agui_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingStopPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingStopPayload) ProtoMessage() {}

func (x *ThinkingStopPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingStopPayload.ProtoReflect.Descriptor instead.
func (*ThinkingStopPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{12}
}

func (x *ThinkingStopPayload) GetThinkingId() string {
	if x != nil {
		return x.ThinkingId
	}
	return ""
}

func (x *ThinkingStopPayload) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// TaskStartPayload signals the creation/start of a task
type TaskStartPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ContextId     string                 `protobuf:"bytes,2,opt,name=context_id,json=contextId,proto3" json:"context_id,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // Task description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskStartPayload) Reset() {
	*x = TaskStartPayload{}
	mi := &file_agui_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskStartPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskStartPayload) ProtoMessage() {}

func (x *TaskStartPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskStartPayload.ProtoReflect.Descriptor instead.
func (*TaskStartPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{13}
}

func (x *TaskStartPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskStartPayload) GetContextId() string {
	if x != nil {
		return x.ContextId
	}
	return ""
}

func (x *TaskStartPayload) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// TaskUpdatePayload provides task status updates
type TaskUpdatePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "submitted" | "working" | "input_required" | etc.
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskUpdatePayload) Reset() {
	*x = TaskUpdatePayload{}
	mi := &file_agui_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskUpdatePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskUpdatePayload) ProtoMessage() {}

func (x *TaskUpdatePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskUpdatePayload.ProtoReflect.Descriptor instead.
func (*TaskUpdatePayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{14}
}

func (x *TaskUpdatePayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskUpdatePayload) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TaskUpdatePayload) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// TaskCompletePayload signals task completion
type TaskCompletePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        *structpb.Struct       `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"` // Task result/artifacts
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskCompletePayload) Reset() {
	*x = TaskCompletePayload{}
	mi := &file_agui_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskCompletePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskCompletePayload) ProtoMessage() {}

func (x *TaskCompletePayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskCompletePayload.ProtoReflect.Descriptor instead.
func (*TaskCompletePayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{15}
}

func (x *TaskCompletePayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskCompletePayload) GetResult() *structpb.Struct {
	if x != nil {
		return x.Result
	}
	return nil
}

// TaskErrorPayload signals task failure
type TaskErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Details       *structpb.Struct       `protobuf:"bytes,4,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskErrorPayload) Reset() {
	*x = TaskErrorPayload{}
	mi := &file_agui_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskErrorPayload) ProtoMessage() {}

func (x *TaskErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agui_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskErrorPayload.ProtoReflect.Descriptor instead.
func (*TaskErrorPayload) Descriptor() ([]byte, []int) {
	return file_agui_proto_rawDescGZIP(), []int{16}
}

func (x *TaskErrorPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskErrorPayload) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskErrorPayload) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *TaskErrorPayload) GetDetails() *structpb.Struct {
	if x != nil {
		return x.Details
	}
	return nil
}

var File_agui_proto protoreflect.FileDescriptor

const file_agui_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"agui.proto\x12\aagui.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xbd\n" +
	"\n" +
	"\tAGUIEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12*\n" +
	"\x04type\x18\x02 \x01(\x0e2\x16.agui.v1.AGUIEventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12C\n" +
	"\rmessage_start\x18\n" +
	" \x01(\v2\x1c.agui.v1.MessageStartPayloadH\x00R\fmessageStart\x12C\n" +
	"\rmessage_delta\x18\v \x01(\v2\x1c.agui.v1.MessageDeltaPayloadH\x00R\fmessageDelta\x12@\n" +
	"\fmessage_stop\x18\f \x01(\v2\x1b.agui.v1.MessageStopPayloadH\x00R\vmessageStop\x12S\n" +
	"\x13content_block_start\x18\x14 \x01(\v2!.agui.v1.ContentBlockStartPayloadH\x00R\x11contentBlockStart\x12S\n" +
	"\x13content_block_delta\x18\x15 \x01(\v2!.agui.v1.ContentBlockDeltaPayloadH\x00R\x11contentBlockDelta\x12P\n" +
	"\x12content_block_stop\x18\x16 \x01(\v2 .agui.v1.ContentBlockStopPayloadH\x00R\x10contentBlockStop\x12G\n" +
	"\x0ftool_call_start\x18\x1e \x01(\v2\x1d.agui.v1.ToolCallStartPayloadH\x00R\rtoolCallStart\x12G\n" +
	"\x0ftool_call_delta\x18\x1f \x01(\v2\x1d.agui.v1.ToolCallDeltaPayloadH\x00R\rtoolCallDelta\x12D\n" +
	"\x0etool_call_stop\x18  \x01(\v2\x1c.agui.v1.ToolCallStopPayloadH\x00R\ftoolCallStop\x12F\n" +
	"\x0ethinking_start\x18( \x01(\v2\x1d.agui.v1.ThinkingStartPayloadH\x00R\rthinkingStart\x12F\n" +
	"\x0ethinking_delta\x18) \x01(\v2\x1d.agui.v1.ThinkingDeltaPayloadH\x00R\rthinkingDelta\x12C\n" +
	"\rthinking_stop\x18* \x01(\v2\x1c.agui.v1.ThinkingStopPayloadH\x00R\fthinkingStop\x12:\n" +
	"\n" +
	"task_start\x182 \x01(\v2\x19.agui.v1.TaskStartPayloadH\x00R\ttaskStart\x12=\n" +
	"\vtask_update\x183 \x01(\v2\x1a.agui.v1.TaskUpdatePayloadH\x00R\n" +
	"taskUpdate\x12C\n" +
	"\rtask_complete\x184 \x01(\v2\x1c.agui.v1.TaskCompletePayloadH\x00R\ftaskComplete\x12:\n" +
	"\n" +
	"task_error\x185 \x01(\v2\x19.agui.v1.TaskErrorPayloadH\x00R\ttaskError\x123\n" +
	"\bmetadata\x18d \x01(\v2\x17.google.protobuf.StructR\bmetadataB\t\n" +
	"\apayload\"\x80\x01\n" +
	"\x13MessageStartPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12\x17\n" +
	"\atask_id\x18\x03 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"J\n" +
	"\x13MessageDeltaPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"3\n" +
	"\x12MessageStopPayload\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"j\n" +
	"\x18ContentBlockStartPayload\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x1d\n" +
	"\n" +
	"block_type\x18\x02 \x01(\tR\tblockType\x12\x14\n" +
	"\x05index\x18\x03 \x01(\x05R\x05index\"K\n" +
	"\x18ContentBlockDeltaPayload\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"4\n" +
	"\x17ContentBlockStopPayload\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\tR\ablockId\"\x84\x01\n" +
	"\x14ToolCallStartPayload\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12-\n" +
	"\x05input\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05input\"]\n" +
	"\x14ToolCallDeltaPayload\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12#\n" +
	"\rpartial_input\x18\x02 \x01(\tR\fpartialInput\"\xba\x01\n" +
	"\x13ToolCallStopPayload\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x128\n" +
	"\vfinal_input\x18\x02 \x01(\v2\x17.google.protobuf.StructR\n" +
	"finalInput\x12\x16\n" +
	"\x06result\x18\x03 \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x19\n" +
	"\bis_error\x18\x05 \x01(\bR\aisError\"M\n" +
	"\x14ThinkingStartPayload\x12\x1f\n" +
	"\vthinking_id\x18\x01 \x01(\tR\n" +
	"thinkingId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"M\n" +
	"\x14ThinkingDeltaPayload\x12\x1f\n" +
	"\vthinking_id\x18\x01 \x01(\tR\n" +
	"thinkingId\x12\x14\n" +
	"\x05delta\x18\x02 \x01(\tR\x05delta\"T\n" +
	"\x13ThinkingStopPayload\x12\x1f\n" +
	"\vthinking_id\x18\x01 \x01(\tR\n" +
	"thinkingId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\"l\n" +
	"\x10TaskStartPayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"context_id\x18\x02 \x01(\tR\tcontextId\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"y\n" +
	"\x11TaskUpdatePayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\"_\n" +
	"\x13TaskCompletePayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12/\n" +
	"\x06result\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06result\"\xa2\x01\n" +
	"\x10TaskErrorPayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x03 \x01(\tR\terrorCode\x121\n" +
	"\adetails\x18\x04 \x01(\v2\x17.google.protobuf.StructR\adetails*\xef\x04\n" +
	"\rAGUIEventType\x12\x1f\n" +
	"\x1bAGUI_EVENT_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGUI_EVENT_TYPE_MESSAGE_START\x10\x01\x12!\n" +
	"\x1dAGUI_EVENT_TYPE_MESSAGE_DELTA\x10\x02\x12 \n" +
	"\x1cAGUI_EVENT_TYPE_MESSAGE_STOP\x10\x03\x12'\n" +
	"#AGUI_EVENT_TYPE_CONTENT_BLOCK_START\x10\x04\x12'\n" +
	"#AGUI_EVENT_TYPE_CONTENT_BLOCK_DELTA\x10\x05\x12&\n" +
	"\"AGUI_EVENT_TYPE_CONTENT_BLOCK_STOP\x10\x06\x12#\n" +
	"\x1fAGUI_EVENT_TYPE_TOOL_CALL_START\x10\a\x12#\n" +
	"\x1fAGUI_EVENT_TYPE_TOOL_CALL_DELTA\x10\b\x12\"\n" +
	"\x1eAGUI_EVENT_TYPE_TOOL_CALL_STOP\x10\t\x12\"\n" +
	"\x1eAGUI_EVENT_TYPE_THINKING_START\x10\n" +
	"\x12\"\n" +
	"\x1eAGUI_EVENT_TYPE_THINKING_DELTA\x10\v\x12!\n" +
	"\x1dAGUI_EVENT_TYPE_THINKING_STOP\x10\f\x12\x1e\n" +
	"\x1aAGUI_EVENT_TYPE_TASK_START\x10\r\x12\x1f\n" +
	"\x1bAGUI_EVENT_TYPE_TASK_UPDATE\x10\x0e\x12!\n" +
	"\x1dAGUI_EVENT_TYPE_TASK_COMPLETE\x10\x0f\x12\x1e\n" +
	"\x1aAGUI_EVENT_TYPE_TASK_ERROR\x10\x10B-Z+github.com/kadirpekel/hector/pkg/agui/pb;pbb\x06proto3"

var (
	file_agui_proto_rawDescOnce sync.Once
	file_agui_proto_rawDescData []byte
)

func file_agui_proto_rawDescGZIP() []byte {
	file_agui_proto_rawDescOnce.Do(func() {
		file_agui_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agui_proto_rawDesc), len(file_agui_proto_rawDesc)))
	})
	return file_agui_proto_rawDescData
}

var file_agui_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agui_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_agui_proto_goTypes = []any{
	(AGUIEventType)(0),               // 0: agui.v1.AGUIEventType
	(*AGUIEvent)(nil),                // 1: agui.v1.AGUIEvent
	(*MessageStartPayload)(nil),      // 2: agui.v1.MessageStartPayload
	(*MessageDeltaPayload)(nil),      // 3: agui.v1.MessageDeltaPayload
	(*MessageStopPayload)(nil),       // 4: agui.v1.MessageStopPayload
	(*ContentBlockStartPayload)(nil), // 5: agui.v1.ContentBlockStartPayload
	(*ContentBlockDeltaPayload)(nil), // 6: agui.v1.ContentBlockDeltaPayload
	(*ContentBlockStopPayload)(nil),  // 7: agui.v1.ContentBlockStopPayload
	(*ToolCallStartPayload)(nil),     // 8: agui.v1.ToolCallStartPayload
	(*ToolCallDeltaPayload)(nil),     // 9: agui.v1.ToolCallDeltaPayload
	(*ToolCallStopPayload)(nil),      // 10: agui.v1.ToolCallStopPayload
	(*ThinkingStartPayload)(nil),     // 11: agui.v1.ThinkingStartPayload
	(*ThinkingDeltaPayload)(nil),     // 12: agui.v1.ThinkingDeltaPayload
	(*ThinkingStopPayload)(nil),      // 13: agui.v1.ThinkingStopPayload
	(*TaskStartPayload)(nil),         // 14: agui.v1.TaskStartPayload
	(*TaskUpdatePayload)(nil),        // 15: agui.v1.TaskUpdatePayload
	(*TaskCompletePayload)(nil),      // 16: agui.v1.TaskCompletePayload
	(*TaskErrorPayload)(nil),         // 17: agui.v1.TaskErrorPayload
	(*timestamppb.Timestamp)(nil),    // 18: google.protobuf.Timestamp
	(*structpb.Struct)(nil),          // 19: google.protobuf.Struct
}
var file_agui_proto_depIdxs = []int32{
	0,  // 0: agui.v1.AGUIEvent.type:type_name -> agui.v1.AGUIEventType
	18, // 1: agui.v1.AGUIEvent.timestamp:type_name -> google.protobuf.Timestamp
	2,  // 2: agui.v1.AGUIEvent.message_start:type_name -> agui.v1.MessageStartPayload
	3,  // 3: agui.v1.AGUIEvent.message_delta:type_name -> agui.v1.MessageDeltaPayload
	4,  // 4: agui.v1.AGUIEvent.message_stop:type_name -> agui.v1.MessageStopPayload
	5,  // 5: agui.v1.AGUIEvent.content_block_start:type_name -> agui.v1.ContentBlockStartPayload
	6,  // 6: agui.v1.AGUIEvent.content_block_delta:type_name -> agui.v1.ContentBlockDeltaPayload
	7,  // 7: agui.v1.AGUIEvent.content_block_stop:type_name -> agui.v1.ContentBlockStopPayload
	8,  // 8: agui.v1.AGUIEvent.tool_call_start:type_name -> agui.v1.ToolCallStartPayload
	9,  // 9: agui.v1.AGUIEvent.tool_call_delta:type_name -> agui.v1.ToolCallDeltaPayload
	10, // 10: agui.v1.AGUIEvent.tool_call_stop:type_name -> agui.v1.ToolCallStopPayload
	11, // 11: agui.v1.AGUIEvent.thinking_start:type_name -> agui.v1.ThinkingStartPayload
	12, // 12: agui.v1.AGUIEvent.thinking_delta:type_name -> agui.v1.ThinkingDeltaPayload
	13, // 13: agui.v1.AGUIEvent.thinking_stop:type_name -> agui.v1.ThinkingStopPayload
	14, // 14: agui.v1.AGUIEvent.task_start:type_name -> agui.v1.TaskStartPayload
	15, // 15: agui.v1.AGUIEvent.task_update:type_name -> agui.v1.TaskUpdatePayload
	16, // 16: agui.v1.AGUIEvent.task_complete:type_name -> agui.v1.TaskCompletePayload
	17, // 17: agui.v1.AGUIEvent.task_error:type_name -> agui.v1.TaskErrorPayload
	19, // 18: agui.v1.AGUIEvent.metadata:type_name -> google.protobuf.Struct
	19, // 19: agui.v1.ToolCallStartPayload.input:type_name -> google.protobuf.Struct
	19, // 20: agui.v1.ToolCallStopPayload.final_input:type_name -> google.protobuf.Struct
	19, // 21: agui.v1.TaskUpdatePayload.metadata:type_name -> google.protobuf.Struct
	19, // 22: agui.v1.TaskCompletePayload.result:type_name -> google.protobuf.Struct
	19, // 23: agui.v1.TaskErrorPayload.details:type_name -> google.protobuf.Struct
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_agui_proto_init() }
func file_agui_proto_init() {
	if File_agui_proto != nil {
		return
	}
	file_agui_proto_msgTypes[0].OneofWrappers = []any{
		(*AGUIEvent_MessageStart)(nil),
		(*AGUIEvent_MessageDelta)(nil),
		(*AGUIEvent_MessageStop)(nil),
		(*AGUIEvent_ContentBlockStart)(nil),
		(*AGUIEvent_ContentBlockDelta)(nil),
		(*AGUIEvent_ContentBlockStop)(nil),
		(*AGUIEvent_ToolCallStart)(nil),
		(*AGUIEvent_ToolCallDelta)(nil),
		(*AGUIEvent_ToolCallStop)(nil),
		(*AGUIEvent_ThinkingStart)(nil),
		(*AGUIEvent_ThinkingDelta)(nil),
		(*AGUIEvent_ThinkingStop)(nil),
		(*AGUIEvent_TaskStart)(nil),
		(*AGUIEvent_TaskUpdate)(nil),
		(*AGUIEvent_TaskComplete)(nil),
		(*AGUIEvent_TaskError)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agui_proto_rawDesc), len(file_agui_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agui_proto_goTypes,
		DependencyIndexes: file_agui_proto_depIdxs,
		EnumInfos:         file_agui_proto_enumTypes,
		MessageInfos:      file_agui_proto_msgTypes,
	}.Build()
	File_agui_proto = out.File
	file_agui_proto_goTypes = nil
	file_agui_proto_depIdxs = nil
}
