// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: embedder.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EmbedRequest requests embeddings for text
type EmbedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedRequest) Reset() {
	*x = EmbedRequest{}
	mi := &file_embedder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedRequest) ProtoMessage() {}

func (x *EmbedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedRequest.ProtoReflect.Descriptor instead.
func (*EmbedRequest) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// EmbedResponse returns the embedding vector
type EmbedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedResponse) Reset() {
	*x = EmbedResponse{}
	mi := &file_embedder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedResponse) ProtoMessage() {}

func (x *EmbedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedResponse.ProtoReflect.Descriptor instead.
func (*EmbedResponse) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedResponse) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *EmbedResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// EmbedderInfo returns information about the embedder
type EmbedderInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelName     string                 `protobuf:"bytes,1,opt,name=model_name,json=modelName,proto3" json:"model_name,omitempty"`
	Dimension     int32                  `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedderInfo) Reset() {
	*x = EmbedderInfo{}
	mi := &file_embedder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedderInfo) ProtoMessage() {}

func (x *EmbedderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_embedder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedderInfo.ProtoReflect.Descriptor instead.
func (*EmbedderInfo) Descriptor() ([]byte, []int) {
	return file_embedder_proto_rawDescGZIP(), []int{2}
}

func (x *EmbedderInfo) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *EmbedderInfo) GetDimension() int32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

var File_embedder_proto protoreflect.FileDescriptor

const file_embedder_proto_rawDesc = "" +
	"\n" +
	"\x0eembedder.proto\x12\rhector.plugin\x1a\fcommon.proto\"\"\n" +
	"\fEmbedRequest\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"=\n" +
	"\rEmbedResponse\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"K\n" +
	"\fEmbedderInfo\x12\x1d\n" +
	"\n" +
	"model_name\x18\x01 \x01(\tR\tmodelName\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\x05R\tdimension2\x9d\x04\n" +
	"\x10EmbedderProvider\x12Q\n" +
	"\n" +
	"Initialize\x12 .hector.plugin.InitializeRequest\x1a!.hector.plugin.InitializeResponse\x12K\n" +
	"\bShutdown\x12\x1e.hector.plugin.ShutdownRequest\x1a\x1f.hector.plugin.ShutdownResponse\x12E\n" +
	"\x06Health\x12\x1c.hector.plugin.HealthRequest\x1a\x1d.hector.plugin.HealthResponse\x12N\n" +
	"\vGetManifest\x12\x1e.hector.plugin.ManifestRequest\x1a\x1f.hector.plugin.ManifestResponse\x12H\n" +
	"\tGetStatus\x12\x1c.hector.plugin.StatusRequest\x1a\x1d.hector.plugin.StatusResponse\x12B\n" +
	"\x05Embed\x12\x1b.hector.plugin.EmbedRequest\x1a\x1c.hector.plugin.EmbedResponse\x12D\n" +
	"\x0fGetEmbedderInfo\x12\x14.hector.plugin.Empty\x1a\x1b.hector.plugin.EmbedderInfoB1Z/github.com/kadirpekel/hector/plugins/grpc/protob\x06proto3"

var (
	file_embedder_proto_rawDescOnce sync.Once
	file_embedder_proto_rawDescData []byte
)

func file_embedder_proto_rawDescGZIP() []byte {
	file_embedder_proto_rawDescOnce.Do(func() {
		file_embedder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_embedder_proto_rawDesc), len(file_embedder_proto_rawDesc)))
	})
	return file_embedder_proto_rawDescData
}

var file_embedder_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_embedder_proto_goTypes = []any{
	(*EmbedRequest)(nil),       // 0: hector.plugin.EmbedRequest
	(*EmbedResponse)(nil),      // 1: hector.plugin.EmbedResponse
	(*EmbedderInfo)(nil),       // 2: hector.plugin.EmbedderInfo
	(*InitializeRequest)(nil),  // 3: hector.plugin.InitializeRequest
	(*ShutdownRequest)(nil),    // 4: hector.plugin.ShutdownRequest
	(*HealthRequest)(nil),      // 5: hector.plugin.HealthRequest
	(*ManifestRequest)(nil),    // 6: hector.plugin.ManifestRequest
	(*StatusRequest)(nil),      // 7: hector.plugin.StatusRequest
	(*Empty)(nil),              // 8: hector.plugin.Empty
	(*InitializeResponse)(nil), // 9: hector.plugin.InitializeResponse
	(*ShutdownResponse)(nil),   // 10: hector.plugin.ShutdownResponse
	(*HealthResponse)(nil),     // 11: hector.plugin.HealthResponse
	(*ManifestResponse)(nil),   // 12: hector.plugin.ManifestResponse
	(*StatusResponse)(nil),     // 13: hector.plugin.StatusResponse
}
var file_embedder_proto_depIdxs = []int32{
	3,  // 0: hector.plugin.EmbedderProvider.Initialize:input_type -> hector.plugin.InitializeRequest
	4,  // 1: hector.plugin.EmbedderProvider.Shutdown:input_type -> hector.plugin.ShutdownRequest
	5,  // 2: hector.plugin.EmbedderProvider.Health:input_type -> hector.plugin.HealthRequest
	6,  // 3: hector.plugin.EmbedderProvider.GetManifest:input_type -> hector.plugin.ManifestRequest
	7,  // 4: hector.plugin.EmbedderProvider.GetStatus:input_type -> hector.plugin.StatusRequest
	0,  // 5: hector.plugin.EmbedderProvider.Embed:input_type -> hector.plugin.EmbedRequest
	8,  // 6: hector.plugin.EmbedderProvider.GetEmbedderInfo:input_type -> hector.plugin.Empty
	9,  // 7: hector.plugin.EmbedderProvider.Initialize:output_type -> hector.plugin.InitializeResponse
	10, // 8: hector.plugin.EmbedderProvider.Shutdown:output_type -> hector.plugin.ShutdownResponse
	11, // 9: hector.plugin.EmbedderProvider.Health:output_type -> hector.plugin.HealthResponse
	12, // 10: hector.plugin.EmbedderProvider.GetManifest:output_type -> hector.plugin.ManifestResponse
	13, // 11: hector.plugin.EmbedderProvider.GetStatus:output_type -> hector.plugin.StatusResponse
	1,  // 12: hector.plugin.EmbedderProvider.Embed:output_type -> hector.plugin.EmbedResponse
	2,  // 13: hector.plugin.EmbedderProvider.GetEmbedderInfo:output_type -> hector.plugin.EmbedderInfo
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_embedder_proto_init() }
func file_embedder_proto_init() {
	if File_embedder_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_embedder_proto_rawDesc), len(file_embedder_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_embedder_proto_goTypes,
		DependencyIndexes: file_embedder_proto_depIdxs,
		MessageInfos:      file_embedder_proto_msgTypes,
	}.Build()
	File_embedder_proto = out.File
	file_embedder_proto_goTypes = nil
	file_embedder_proto_depIdxs = nil
}
