# Minimal Config Example
# Shows how to override just what you need while keeping defaults for everything else

name: "my-assistant"
description: "Minimal config with custom LLM"

# Override just the LLM, everything else uses defaults
llms:
  gpt4:
    type: "openai"
    model: "gpt-4o"
    api_key: "${OPENAI_API_KEY}"

# The default agent will automatically use this LLM if it's the only one defined
# Or you can explicitly reference it:
agents:
  my-agent:
    llm: "gpt4"
    # Everything else uses defaults
