# A2A Server Configuration - Serves Weather Expert Agent
# This config exposes a weather expert agent via A2A protocol
# Other Hector instances (or any A2A-compliant client) can consume this agent

# Global settings
global:
  a2a_server:
    enabled: true
    host: "0.0.0.0"
    port: 8080

agents:
  weather_expert:
    name: "Weather Expert"
    description: "Specialized weather information agent with real-time weather data access"
    visibility: "public"  # Exposed via A2A discovery
    
    llm: "gpt-llm"
    
    prompt:
      system_prompt: |
        You are a friendly weather information assistant.
        You help users get accurate weather information for any location.
        
        Use the WEATHERMAP_WEATHER tool when you need current weather data.
    
    reasoning:
      engine: "chain-of-thought"
      enable_streaming: true
      show_thinking: false
    
    tools:
      - "WEATHERMAP_WEATHER"  # MCP weather tool

# LLM Configuration
llms:
  gpt-llm:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.3
    max_tokens: 1000
    timeout: 30

# Global Tools (MCP weather service)
tools:
  weather_mcp:
    type: mcp
    enabled: true
    server_url: "${MCP_SERVER_URL}"
    description: "Real-time weather data from OpenWeatherMap"
