# A2A Mixed Orchestration - Both Local and External Agents
# This config demonstrates orchestration with mixed agent types

# Global settings
global:
  a2a_server:
    enabled: true
    host: "0.0.0.0"
    port: 8082  # Different port to avoid conflicts

agents:
  # Orchestrator agent
  research_coordinator:
    name: "Research Coordinator"
    description: "Coordinates research tasks using both local and external agents"
    visibility: "public"
    
    llm: "gpt-llm"
    
    prompt:
      prompt_slots:
        system_role: |
          You are a research coordinator that manages complex inquiries by working with specialized agents.
          
          Your team includes:
          - weather_analyst: Expert in analyzing weather patterns and trends
          - weather_expert: Provides real-time weather data (external service)
        
        reasoning_instructions: |
          When coordinating research:
          - Break complex questions into focused subtasks
          - Route each task to the most appropriate specialist
          - Use agent_call to consult with your team
          - Synthesize findings into clear, actionable insights
    
    reasoning:
      engine: "supervisor"
      enable_streaming: true
      show_thinking: true
      show_tool_execution: true
    
    tools:
      - "agent_call"
  
  # Local agent
  weather_analyst:
    name: "Weather Analyst"
    description: "Analyzes weather patterns, trends, and provides insights"
    visibility: "internal"
    
    llm: "gpt-llm"
    
    prompt:
      prompt_slots:
        system_role: |
          You are a weather analysis expert specializing in patterns, trends, and insights.
          You interpret weather information and provide thoughtful analysis.
          
          Note: You analyze weather data but do not have access to real-time information.
    
    reasoning:
      engine: "chain-of-thought"
      enable_streaming: true
  
  # External agent reference (A2A)
  weather_expert:
    name: "Weather Expert (External)"
    description: "External weather data provider via A2A protocol"
    type: "a2a"
    url: "http://localhost:8080/agents/weather_expert"
    visibility: "internal"

# LLM Configuration
llms:
  gpt-llm:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.7
    max_tokens: 2000
    timeout: 60
