# Auth0 Authentication Test Configuration
# Replace YOUR-TENANT and audience with your Auth0 settings

global:
  a2a_server:
    enabled: true
    host: "0.0.0.0"
    port: 8090
  
  # Authentication configuration for Auth0
  auth:
    enabled: true
    jwks_url: "https://dev-necoi8pbjgvataq6.us.auth0.com/.well-known/jwks.json"
    issuer: "https://dev-necoi8pbjgvataq6.us.auth0.com/"
    audience: "https://github.com/kadirpekel/hector"
    # Optional: require specific scopes
    required_scopes: []

# LLMs
llms:
  gpt:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.7

# Agents
agents:
  test_agent:
    name: "Test Agent"
    description: "Agent for testing authentication"
    visibility: "public"
    
    llm: "gpt"
    
    prompt:
      system_prompt: |
        You are a helpful assistant used for testing authentication.
    
    reasoning:
      engine: "chain-of-thought"
      max_iterations: 5
      enable_streaming: true
