# Echo Plugin Test Configuration
# Tests the complete plugin system integration

global:
  a2a_server:
    enabled: true
    host: "0.0.0.0"
    port: 8090

# Plugin Configuration
plugins:
  llm_providers:
    echo-llm:
      name: "echo-llm"
      type: grpc
      path: "./examples/plugins/echo-llm/echo-llm"
      enabled: true
      config:
        prefix: "🔊 Echo: "

# LLMs (fallback)
llms:
  gpt-llm:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"

# Agent using the plugin
agents:
  echo_agent:
    name: "Echo Agent"
    description: "Tests gRPC plugin system - echoes your messages"
    visibility: "public"
    
    llm: "echo-llm"  # Use the plugin!
    
    prompt:
      system_prompt: |
        You are an echo assistant that demonstrates the Hector plugin system.
    
    reasoning:
      engine: "chain-of-thought"
      max_iterations: 1
      enable_streaming: true