llms:
  gpt4o:
    type: openai
    model: gpt-4o
    api_key: ${OPENAI_API_KEY}
agents:
  default-agent:
    name: default-agent
    llm: gpt4o
    memory:
      strategy: "summary_buffer"  
    reasoning:
      engine: chain-of-thought
      enable_streaming: true
    prompt:
      include_history: true
      system_prompt: |
        You are a helpful assistant with advanced memory management.
  custom-agent:
    name: custom-agent
    llm: gpt4o
    memory:
      strategy: "summary_buffer"
      budget: 3000      
      threshold: 0.75   
      target: 0.5       
    reasoning:
      engine: chain-of-thought
    prompt:
      include_history: true
  simple-agent:
    name: simple-agent
    llm: gpt4o
    memory:
      strategy: "buffer_window"
      window_size: 15   
    reasoning:
      engine: chain-of-thought
    prompt:
      include_history: true
  minimal-agent:
    name: minimal-agent
    llm: gpt4o
    memory:
      strategy: "summary_buffer"  
    prompt:
      include_history: true
  legacy-agent:
    name: legacy-agent
    llm: gpt4o
    memory:
      budget: 2000
      summarization: true  
    prompt:
      include_history: true
