session_stores:
  shared-db:
    backend: sql
    sql:
      driver: sqlite
      database: ./data/shared-sessions.db
      max_conns: 25    
      max_idle: 5
agents:
  assistant:
    name: "General Assistant"
    description: "Helpful assistant for general queries"
    llm: "gpt"
    session_store: "shared-db"  
    reasoning:
      engine: chain-of-thought
      max_iterations: 100
    memory:
      strategy: buffer_window
      window_size: 20
  researcher:
    name: "Research Agent"
    description: "Deep research and analysis specialist"
    llm: "gpt"
    session_store: "shared-db"  
    reasoning:
      engine: chain-of-thought
      max_iterations: 100
    memory:
      strategy: summary_buffer
      budget: 3000
      threshold: 0.8
      target: 0.6
  coder:
    name: "Coding Assistant"
    description: "Programming help and code generation"
    llm: "gpt"
    session_store: "shared-db"  
    reasoning:
      engine: chain-of-thought
      max_iterations: 100
    memory:
      strategy: buffer_window
      window_size: 15
llms:
  gpt:
    type: openai
    model: gpt-4o-mini
    api_key: ${OPENAI_API_KEY}
