global:
  observability:
    metrics:
      enabled: true
    tracing:
      enabled: true
      exporter_type: "otlp"
      endpoint_url: "localhost:4317"
      sampling_rate: 1.0
      service_name: "hector"

llms:
  gpt-4o:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"

agents:
  test-agent:
    name: "Test Agent"
    description: "Agent for observability testing"
    llm: "gpt-4o"
    observability:
      enabled: true
      trace_agent_calls: true
      trace_tool_execution: true
      trace_llm_requests: true
      record_metrics: true

