agents:
  coordinator:
    name: "Research Coordinator"
    description: "Coordinates research tasks using 3 specialist agents"
    llm: "gpt-4o"
    reasoning:
      engine: "supervisor"  
      max_iterations: 10
      enable_streaming: true
    tools:
      - "agent_call"
    prompt:
      system_prompt: |
        You coordinate research tasks using 3 specialists:
        - researcher: Gathers information from web sources
        - analyst: Analyzes findings and identifies insights  
        - writer: Creates structured reports
        Process: researcher → analyst → writer → deliver final report
        Always call agents in sequence and build on previous results.
  researcher:
    name: "Web Researcher"
    description: "Gathers information from web sources"
    llm: "gpt-4o-mini"
    reasoning:
      engine: "chain-of-thought"
      max_iterations: 5
      enable_streaming: true
    tools:
      - "execute_command"
    prompt:
      system_prompt: |
        You research topics by searching the web and gathering information.
        Use curl to search and extract key facts from multiple sources.
        Focus on credible, recent information.
        Provide structured output with:
        - Key findings organized by theme
        - Source URLs and credibility assessment
        - Summary of main insights
  analyst:
    name: "Research Analyst"
    description: "Analyzes research findings to identify key insights"
    llm: "gpt-4o-mini"
    reasoning:
      engine: "chain-of-thought"
      max_iterations: 5
      enable_streaming: true
    prompt:
      system_prompt: |
        You analyze research findings to identify:
        - Key themes and patterns
        - Important insights and trends
        - Gaps or contradictions in the information
        - Implications and significance
        Provide clear, structured analysis that builds on the research data.
  writer:
    name: "Report Writer"
    description: "Creates well-structured reports from research analysis"
    llm: "gpt-4o-mini"
    reasoning:
      engine: "chain-of-thought"
      max_iterations: 5
      enable_streaming: true
    tools:
      - "write_file"
    prompt:
      system_prompt: |
        You create well-structured reports from research analysis.
        Use clear headings, bullet points, and proper citations.
        Save the final report as a markdown file.
        Report structure:
llms:
  gpt-4o:
    type: "openai"
    model: "gpt-4o"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.3  
    max_tokens: 4000
  gpt-4o-mini:
    type: "openai"
    model: "gpt-4o-mini"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.5  
    max_tokens: 3000
tools:
  execute_command:
    type: command
    working_directory: "./"
    max_execution_time: "30s"
    enable_sandboxing: true
  write_file:
    type: write_file
    working_directory: "./reports"
    max_file_size: 1048576  
