providers:
  llms:
    default-llm:
      type: "openai"
      model: "gpt-4o"
      api_key: "${OPENAI_API_KEY}"
agents:
  secure-agent:
    name: "Secure Agent"
    description: "An agent that requires JWT authentication"
    llm: "default-llm"
    security:
      enabled: true
      schemes:
        BearerAuth:
          type: "http"
          scheme: "bearer"
          bearer_format: "JWT"
          description: "JWT Bearer token authentication"
      require:
        - BearerAuth: []  
      jwks_url: "https://your-auth-server.com/.well-known/jwks.json"
      issuer: "https://your-auth-server.com/"
      audience: "your-agent-api"
server:
  auth:
    enabled: true
    jwks_url: "https://your-auth-server.com/.well-known/jwks.json"
    issuer: "https://your-auth-server.com/"
    audience: "your-agent-api"
