# Smoke Test Configuration for Memory Features
# Tests all three tiers of memory configuration

llms:
  gemini:
    type: gemini
    model: gemini-2.0-flash-exp
    api_key: ${GEMINI_API_KEY}
    max_tokens: 8192
    temperature: 0.7

# Test 1: Basic Memory (Tier 1 - 90% of users)
agents:
  basic-memory-test:
    name: basic-memory-test
    description: Tests basic memory with default settings
    llm: gemini
    
    reasoning:
      engine: chain-of-thought
      max_iterations: 5
      show_debug_info: true
      enable_streaming: true
    
    memory:
      budget: 2000              # Main setting - enables memory management
    
    prompt:
      include_history: true
      include_context: true
      system_prompt: |
        You are a test assistant. Keep your responses brief.
        When asked about memory, describe what you remember from our conversation.
    
    tools:
      - execute_command

  # Test 2: Adjusted Memory Budget (Tier 2 - 9% of users)
  large-budget-test:
    name: large-budget-test
    description: Tests memory with larger budget
    llm: gemini
    
    reasoning:
      engine: chain-of-thought
      max_iterations: 5
      show_debug_info: true
    
    memory:
      budget: 3000             # Increased budget
    
    prompt:
      include_history: true
      system_prompt: |
        You are a test assistant with larger memory.
        Keep responses brief but remember everything we discuss.

  # Test 3: Full Features with Summarization (Tier 3 - 1% of users)
  full-memory-test:
    name: full-memory-test
    description: Tests all memory features including summarization
    llm: gemini
    
    reasoning:
      engine: chain-of-thought
      max_iterations: 5
      show_debug_info: true
    
    memory:
      budget: 3000
      summarization: true      # Summarization enabled
    
    prompt:
      include_history: true
      system_prompt: |
        You are a test assistant with full memory features.
        Keep responses brief but comprehensive.


server:
  host: 0.0.0.0
  port: 8080
  enable_cors: true

# Smoke Test Instructions:
#
# 1. Set your Gemini API key:
#    export GEMINI_API_KEY="your-key-here"
#
# 2. Start the server:
#    ./hector serve --config configs/smoke-test-memory.yaml
#
# 3. Test each agent:
#    
#    Test 1 - Basic Memory (90% of users):
#    curl -X POST http://localhost:8080/v1/agents/basic-memory-test/chat \
#      -H "Content-Type: application/json" \
#      -d '{"message": "Hello, remember this: I like pizza"}'
#    
#    curl -X POST http://localhost:8080/v1/agents/basic-memory-test/chat \
#      -H "Content-Type: application/json" \
#      -d '{"message": "What do I like?"}'
#    
#    Test 2 - Larger Budget (9% of users):
#    curl -X POST http://localhost:8080/v1/agents/large-budget-test/chat \
#      -H "Content-Type: application/json" \
#      -d '{"message": "Test with more context"}'
#    
#    Test 3 - Full Features (1% of users):
#    curl -X POST http://localhost:8080/v1/agents/full-memory-test/chat \
#      -H "Content-Type: application/json" \
#      -d '{"message": "Test summarization"}'
#
# 4. Check logs for:
#    - Token counts (should be accurate)
#    - Memory budget utilization
#    - Summarization triggers (if enabled)
#    - No errors or warnings
#
# 5. Expected behavior:
#    - Basic: Remembers context within 2000 tokens
#    - Large: Remembers more (3000 tokens)
#    - Full: Summarizes when needed
