providers:
  llms:
    default:
      type: openai
      model: gpt-4
      host: https://api.openai.com/v1
      api_key: ${OPENAI_API_KEY}
      temperature: 0.7
      max_tokens: 2000

agents:
  task_agent:
    name: "Task Tracking Agent"
    description: "Agent with full A2A task tracking enabled"
    llm: default
    
    task:
      enabled: true
      backend: memory
    
    memory:
      strategy: buffer_window
      window_size: 20
    
    reasoning:
      engine: react
      max_iterations: 5
    
    tools:
      - web_search
      - calculator

server:
  host: "0.0.0.0"
  port: 50051
  mode: multi

