# Minimal configuration for observability testing
# No document indexing, no complex features - just basic agent with metrics

global:
  observability:
    metrics_enabled: true
    tracing:
      enabled: false

llms:
  claude:
    type: "anthropic"
    model: "claude-sonnet-4-20250514"
    api_key: "${ANTHROPIC_API_KEY}"
    temperature: 0.0
    max_tokens: 1000

agents:
  test-agent:
    name: "Test Agent"
    description: "Simple test agent for observability validation"
    llm: "claude"
    enable_tools: false  # Disable tools for faster startup
    # No docs_folder - skip document indexing
    observability:
      enabled: true
      trace_agent_calls: false
      trace_tool_execution: false
      trace_llm_requests: false
      record_metrics: true
    a2a:
      version: "1.0.0"
      input_modes:
        - "text/plain"
      output_modes:
        - "text/plain"
      skills:
        - id: "test"
          name: "Test Skill"
          description: "Simple test skill"
          tags: ["test"]
          examples:
            - "Hello"
