name: "Visibility Test Configuration"

llms:
  anthropic:
    provider: anthropic
    model: claude-sonnet-4-20250514
    base_url: https://api.anthropic.com/v1
    max_tokens: 8192
    temperature: 1.0

agents:
  public_agent:
    name: "Public Agent"
    description: "Publicly accessible agent"
    visibility: "public"
    llm: anthropic
    reasoning:
      engine: chain-of-thought
      max_iterations: 99

  internal_agent:
    name: "Internal Agent"
    description: "Internal use only - requires authentication"
    visibility: "internal"
    llm: anthropic
    reasoning:
      engine: chain-of-thought
      max_iterations: 99

  private_agent:
    name: "Private Agent"
    description: "Private agent - restricted access"
    visibility: "private"
    llm: anthropic
    reasoning:
      engine: chain-of-thought
      max_iterations: 99

