// Content Blocks Extension for A2A Protocol
// This is an OPTIONAL extension that provides structured content blocks
// for representing thinking/reasoning, planning, and other internal agent states.
//
// This extension is backward compatible with the core A2A protocol and does not
// modify existing message structures. Clients that don't understand content blocks
// can safely ignore them.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: content_blocks.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ContentBlockType defines the type of content block.
// This aligns with industry standards from Anthropic Claude, Vercel AI SDK,
// and LangChain content block patterns.
type ContentBlockType int32

const (
	ContentBlockType_CONTENT_BLOCK_TYPE_UNSPECIFIED ContentBlockType = 0
	// Regular text content
	ContentBlockType_CONTENT_BLOCK_TYPE_TEXT ContentBlockType = 1
	// Internal reasoning/thinking (Anthropic-style)
	ContentBlockType_CONTENT_BLOCK_TYPE_THINKING ContentBlockType = 2
	// Reasoning blocks (Vercel AI SDK style, alias for thinking)
	ContentBlockType_CONTENT_BLOCK_TYPE_REASONING ContentBlockType = 3
	// Tool/function call
	ContentBlockType_CONTENT_BLOCK_TYPE_TOOL_CALL ContentBlockType = 4
	// Tool/function result
	ContentBlockType_CONTENT_BLOCK_TYPE_TOOL_RESULT ContentBlockType = 5
	// Self-reflection on progress
	ContentBlockType_CONTENT_BLOCK_TYPE_REFLECTION ContentBlockType = 6
	// Task planning and todos
	ContentBlockType_CONTENT_BLOCK_TYPE_PLANNING ContentBlockType = 7
	// Progress updates
	ContentBlockType_CONTENT_BLOCK_TYPE_PROGRESS ContentBlockType = 8
	// Debug information
	ContentBlockType_CONTENT_BLOCK_TYPE_DEBUG ContentBlockType = 9
	// Analysis of results
	ContentBlockType_CONTENT_BLOCK_TYPE_ANALYSIS ContentBlockType = 10
)

// Enum value maps for ContentBlockType.
var (
	ContentBlockType_name = map[int32]string{
		0:  "CONTENT_BLOCK_TYPE_UNSPECIFIED",
		1:  "CONTENT_BLOCK_TYPE_TEXT",
		2:  "CONTENT_BLOCK_TYPE_THINKING",
		3:  "CONTENT_BLOCK_TYPE_REASONING",
		4:  "CONTENT_BLOCK_TYPE_TOOL_CALL",
		5:  "CONTENT_BLOCK_TYPE_TOOL_RESULT",
		6:  "CONTENT_BLOCK_TYPE_REFLECTION",
		7:  "CONTENT_BLOCK_TYPE_PLANNING",
		8:  "CONTENT_BLOCK_TYPE_PROGRESS",
		9:  "CONTENT_BLOCK_TYPE_DEBUG",
		10: "CONTENT_BLOCK_TYPE_ANALYSIS",
	}
	ContentBlockType_value = map[string]int32{
		"CONTENT_BLOCK_TYPE_UNSPECIFIED": 0,
		"CONTENT_BLOCK_TYPE_TEXT":        1,
		"CONTENT_BLOCK_TYPE_THINKING":    2,
		"CONTENT_BLOCK_TYPE_REASONING":   3,
		"CONTENT_BLOCK_TYPE_TOOL_CALL":   4,
		"CONTENT_BLOCK_TYPE_TOOL_RESULT": 5,
		"CONTENT_BLOCK_TYPE_REFLECTION":  6,
		"CONTENT_BLOCK_TYPE_PLANNING":    7,
		"CONTENT_BLOCK_TYPE_PROGRESS":    8,
		"CONTENT_BLOCK_TYPE_DEBUG":       9,
		"CONTENT_BLOCK_TYPE_ANALYSIS":    10,
	}
)

func (x ContentBlockType) Enum() *ContentBlockType {
	p := new(ContentBlockType)
	*p = x
	return p
}

func (x ContentBlockType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentBlockType) Descriptor() protoreflect.EnumDescriptor {
	return file_content_blocks_proto_enumTypes[0].Descriptor()
}

func (ContentBlockType) Type() protoreflect.EnumType {
	return &file_content_blocks_proto_enumTypes[0]
}

func (x ContentBlockType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentBlockType.Descriptor instead.
func (ContentBlockType) EnumDescriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{0}
}

// StreamEventType defines lifecycle events for streaming content blocks.
// This follows the Anthropic streaming pattern: start → delta → stop
type StreamEventType int32

const (
	StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED         StreamEventType = 0
	StreamEventType_STREAM_EVENT_TYPE_MESSAGE_START       StreamEventType = 1
	StreamEventType_STREAM_EVENT_TYPE_CONTENT_BLOCK_START StreamEventType = 2
	StreamEventType_STREAM_EVENT_TYPE_CONTENT_BLOCK_DELTA StreamEventType = 3
	StreamEventType_STREAM_EVENT_TYPE_CONTENT_BLOCK_STOP  StreamEventType = 4
	StreamEventType_STREAM_EVENT_TYPE_MESSAGE_DELTA       StreamEventType = 5
	StreamEventType_STREAM_EVENT_TYPE_MESSAGE_STOP        StreamEventType = 6
	StreamEventType_STREAM_EVENT_TYPE_PING                StreamEventType = 7
)

// Enum value maps for StreamEventType.
var (
	StreamEventType_name = map[int32]string{
		0: "STREAM_EVENT_TYPE_UNSPECIFIED",
		1: "STREAM_EVENT_TYPE_MESSAGE_START",
		2: "STREAM_EVENT_TYPE_CONTENT_BLOCK_START",
		3: "STREAM_EVENT_TYPE_CONTENT_BLOCK_DELTA",
		4: "STREAM_EVENT_TYPE_CONTENT_BLOCK_STOP",
		5: "STREAM_EVENT_TYPE_MESSAGE_DELTA",
		6: "STREAM_EVENT_TYPE_MESSAGE_STOP",
		7: "STREAM_EVENT_TYPE_PING",
	}
	StreamEventType_value = map[string]int32{
		"STREAM_EVENT_TYPE_UNSPECIFIED":         0,
		"STREAM_EVENT_TYPE_MESSAGE_START":       1,
		"STREAM_EVENT_TYPE_CONTENT_BLOCK_START": 2,
		"STREAM_EVENT_TYPE_CONTENT_BLOCK_DELTA": 3,
		"STREAM_EVENT_TYPE_CONTENT_BLOCK_STOP":  4,
		"STREAM_EVENT_TYPE_MESSAGE_DELTA":       5,
		"STREAM_EVENT_TYPE_MESSAGE_STOP":        6,
		"STREAM_EVENT_TYPE_PING":                7,
	}
)

func (x StreamEventType) Enum() *StreamEventType {
	p := new(StreamEventType)
	*p = x
	return p
}

func (x StreamEventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StreamEventType) Descriptor() protoreflect.EnumDescriptor {
	return file_content_blocks_proto_enumTypes[1].Descriptor()
}

func (StreamEventType) Type() protoreflect.EnumType {
	return &file_content_blocks_proto_enumTypes[1]
}

func (x StreamEventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StreamEventType.Descriptor instead.
func (StreamEventType) EnumDescriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{1}
}

// ContentBlock represents a structured unit of content with lifecycle management.
// This follows the Anthropic Claude content block pattern which is becoming
// an industry standard.
type ContentBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this content block within the message
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Type of the content block
	Type ContentBlockType `protobuf:"varint,2,opt,name=type,proto3,enum=a2a.v1.extensions.ContentBlockType" json:"type,omitempty"`
	// The actual block content
	//
	// Types that are valid to be assigned to Block:
	//
	//	*ContentBlock_TextBlock
	//	*ContentBlock_ThinkingBlock
	//	*ContentBlock_ToolCallBlock
	//	*ContentBlock_ToolResultBlock
	//	*ContentBlock_ReasoningBlock
	Block isContentBlock_Block `protobuf_oneof:"block"`
	// Optional metadata for extensibility
	Metadata      map[string]string `protobuf:"bytes,20,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlock) Reset() {
	*x = ContentBlock{}
	mi := &file_content_blocks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlock) ProtoMessage() {}

func (x *ContentBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlock.ProtoReflect.Descriptor instead.
func (*ContentBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{0}
}

func (x *ContentBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContentBlock) GetType() ContentBlockType {
	if x != nil {
		return x.Type
	}
	return ContentBlockType_CONTENT_BLOCK_TYPE_UNSPECIFIED
}

func (x *ContentBlock) GetBlock() isContentBlock_Block {
	if x != nil {
		return x.Block
	}
	return nil
}

func (x *ContentBlock) GetTextBlock() *TextBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_TextBlock); ok {
			return x.TextBlock
		}
	}
	return nil
}

func (x *ContentBlock) GetThinkingBlock() *ThinkingBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ThinkingBlock); ok {
			return x.ThinkingBlock
		}
	}
	return nil
}

func (x *ContentBlock) GetToolCallBlock() *ToolCallBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ToolCallBlock); ok {
			return x.ToolCallBlock
		}
	}
	return nil
}

func (x *ContentBlock) GetToolResultBlock() *ToolResultBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ToolResultBlock); ok {
			return x.ToolResultBlock
		}
	}
	return nil
}

func (x *ContentBlock) GetReasoningBlock() *ReasoningBlock {
	if x != nil {
		if x, ok := x.Block.(*ContentBlock_ReasoningBlock); ok {
			return x.ReasoningBlock
		}
	}
	return nil
}

func (x *ContentBlock) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type isContentBlock_Block interface {
	isContentBlock_Block()
}

type ContentBlock_TextBlock struct {
	TextBlock *TextBlock `protobuf:"bytes,10,opt,name=text_block,json=textBlock,proto3,oneof"`
}

type ContentBlock_ThinkingBlock struct {
	ThinkingBlock *ThinkingBlock `protobuf:"bytes,11,opt,name=thinking_block,json=thinkingBlock,proto3,oneof"`
}

type ContentBlock_ToolCallBlock struct {
	ToolCallBlock *ToolCallBlock `protobuf:"bytes,12,opt,name=tool_call_block,json=toolCallBlock,proto3,oneof"`
}

type ContentBlock_ToolResultBlock struct {
	ToolResultBlock *ToolResultBlock `protobuf:"bytes,13,opt,name=tool_result_block,json=toolResultBlock,proto3,oneof"`
}

type ContentBlock_ReasoningBlock struct {
	ReasoningBlock *ReasoningBlock `protobuf:"bytes,14,opt,name=reasoning_block,json=reasoningBlock,proto3,oneof"`
}

func (*ContentBlock_TextBlock) isContentBlock_Block() {}

func (*ContentBlock_ThinkingBlock) isContentBlock_Block() {}

func (*ContentBlock_ToolCallBlock) isContentBlock_Block() {}

func (*ContentBlock_ToolResultBlock) isContentBlock_Block() {}

func (*ContentBlock_ReasoningBlock) isContentBlock_Block() {}

// TextBlock contains plain text content
type TextBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextBlock) Reset() {
	*x = TextBlock{}
	mi := &file_content_blocks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextBlock) ProtoMessage() {}

func (x *TextBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextBlock.ProtoReflect.Descriptor instead.
func (*TextBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{1}
}

func (x *TextBlock) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ThinkingBlock contains internal reasoning/thinking content.
// This follows Anthropic Claude's extended thinking pattern.
type ThinkingBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The thinking/reasoning content
	Thinking string `protobuf:"bytes,1,opt,name=thinking,proto3" json:"thinking,omitempty"`
	// Optional signature for integrity verification (Anthropic-style)
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	// Display metadata for UI rendering hints
	Metadata      *ThinkingMetadata `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingBlock) Reset() {
	*x = ThinkingBlock{}
	mi := &file_content_blocks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingBlock) ProtoMessage() {}

func (x *ThinkingBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingBlock.ProtoReflect.Descriptor instead.
func (*ThinkingBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{2}
}

func (x *ThinkingBlock) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

func (x *ThinkingBlock) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ThinkingBlock) GetMetadata() *ThinkingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ThinkingMetadata provides UI rendering hints without enforcing specific display logic.
// This allows different media (CLI, Web, Mobile) to interpret hints appropriately.
type ThinkingMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional title for the thinking block
	Title string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	// Whether the content can be collapsed in UI (default: false)
	Collapsible bool `protobuf:"varint,2,opt,name=collapsible,proto3" json:"collapsible,omitempty"`
	// Priority level for display decisions (0=low, 1=medium, 2=high)
	Priority int32 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	// Whether this content is ephemeral and can be hidden after completion
	Ephemeral bool `protobuf:"varint,4,opt,name=ephemeral,proto3" json:"ephemeral,omitempty"`
	// Tags for categorization and filtering
	Tags []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	// Content format hint: "markdown", "json", "plain"
	Format string `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	// Custom attributes for domain-specific needs
	Attributes    map[string]string `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingMetadata) Reset() {
	*x = ThinkingMetadata{}
	mi := &file_content_blocks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingMetadata) ProtoMessage() {}

func (x *ThinkingMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingMetadata.ProtoReflect.Descriptor instead.
func (*ThinkingMetadata) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{3}
}

func (x *ThinkingMetadata) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ThinkingMetadata) GetCollapsible() bool {
	if x != nil {
		return x.Collapsible
	}
	return false
}

func (x *ThinkingMetadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *ThinkingMetadata) GetEphemeral() bool {
	if x != nil {
		return x.Ephemeral
	}
	return false
}

func (x *ThinkingMetadata) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ThinkingMetadata) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ThinkingMetadata) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// ReasoningBlock is an alias for ThinkingBlock to match Vercel AI SDK terminology
type ReasoningBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reasoning     string                 `protobuf:"bytes,1,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	Signature     string                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	Metadata      *ThinkingMetadata      `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReasoningBlock) Reset() {
	*x = ReasoningBlock{}
	mi := &file_content_blocks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReasoningBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReasoningBlock) ProtoMessage() {}

func (x *ReasoningBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReasoningBlock.ProtoReflect.Descriptor instead.
func (*ReasoningBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{4}
}

func (x *ReasoningBlock) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

func (x *ReasoningBlock) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ReasoningBlock) GetMetadata() *ThinkingMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ToolCallBlock represents a tool/function invocation
type ToolCallBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this tool call
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name of the tool being called
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Tool input as JSON string
	Input         string `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolCallBlock) Reset() {
	*x = ToolCallBlock{}
	mi := &file_content_blocks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolCallBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolCallBlock) ProtoMessage() {}

func (x *ToolCallBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolCallBlock.ProtoReflect.Descriptor instead.
func (*ToolCallBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{5}
}

func (x *ToolCallBlock) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolCallBlock) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolCallBlock) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

// ToolResultBlock contains the result of a tool execution
type ToolResultBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the tool call this result corresponds to
	ToolCallId string `protobuf:"bytes,1,opt,name=tool_call_id,json=toolCallId,proto3" json:"tool_call_id,omitempty"`
	// Result content
	Content string `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	// Whether this result represents an error
	IsError       bool `protobuf:"varint,3,opt,name=is_error,json=isError,proto3" json:"is_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolResultBlock) Reset() {
	*x = ToolResultBlock{}
	mi := &file_content_blocks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolResultBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolResultBlock) ProtoMessage() {}

func (x *ToolResultBlock) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolResultBlock.ProtoReflect.Descriptor instead.
func (*ToolResultBlock) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{6}
}

func (x *ToolResultBlock) GetToolCallId() string {
	if x != nil {
		return x.ToolCallId
	}
	return ""
}

func (x *ToolResultBlock) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ToolResultBlock) GetIsError() bool {
	if x != nil {
		return x.IsError
	}
	return false
}

// StreamEvent represents a streaming lifecycle event for content blocks
type StreamEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Event type
	Type StreamEventType `protobuf:"varint,1,opt,name=type,proto3,enum=a2a.v1.extensions.StreamEventType" json:"type,omitempty"`
	// Event payload
	//
	// Types that are valid to be assigned to Event:
	//
	//	*StreamEvent_MessageStart
	//	*StreamEvent_ContentBlockStart
	//	*StreamEvent_ContentBlockDelta
	//	*StreamEvent_ContentBlockStop
	//	*StreamEvent_MessageDelta
	//	*StreamEvent_MessageStop
	//	*StreamEvent_Ping
	Event         isStreamEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEvent) Reset() {
	*x = StreamEvent{}
	mi := &file_content_blocks_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEvent) ProtoMessage() {}

func (x *StreamEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEvent.ProtoReflect.Descriptor instead.
func (*StreamEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{7}
}

func (x *StreamEvent) GetType() StreamEventType {
	if x != nil {
		return x.Type
	}
	return StreamEventType_STREAM_EVENT_TYPE_UNSPECIFIED
}

func (x *StreamEvent) GetEvent() isStreamEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *StreamEvent) GetMessageStart() *MessageStartEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStart); ok {
			return x.MessageStart
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStart() *ContentBlockStartEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStart); ok {
			return x.ContentBlockStart
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockDelta() *ContentBlockDeltaEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockDelta); ok {
			return x.ContentBlockDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetContentBlockStop() *ContentBlockStopEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_ContentBlockStop); ok {
			return x.ContentBlockStop
		}
	}
	return nil
}

func (x *StreamEvent) GetMessageDelta() *MessageDeltaEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageDelta); ok {
			return x.MessageDelta
		}
	}
	return nil
}

func (x *StreamEvent) GetMessageStop() *MessageStopEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_MessageStop); ok {
			return x.MessageStop
		}
	}
	return nil
}

func (x *StreamEvent) GetPing() *PingEvent {
	if x != nil {
		if x, ok := x.Event.(*StreamEvent_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isStreamEvent_Event interface {
	isStreamEvent_Event()
}

type StreamEvent_MessageStart struct {
	MessageStart *MessageStartEvent `protobuf:"bytes,10,opt,name=message_start,json=messageStart,proto3,oneof"`
}

type StreamEvent_ContentBlockStart struct {
	ContentBlockStart *ContentBlockStartEvent `protobuf:"bytes,11,opt,name=content_block_start,json=contentBlockStart,proto3,oneof"`
}

type StreamEvent_ContentBlockDelta struct {
	ContentBlockDelta *ContentBlockDeltaEvent `protobuf:"bytes,12,opt,name=content_block_delta,json=contentBlockDelta,proto3,oneof"`
}

type StreamEvent_ContentBlockStop struct {
	ContentBlockStop *ContentBlockStopEvent `protobuf:"bytes,13,opt,name=content_block_stop,json=contentBlockStop,proto3,oneof"`
}

type StreamEvent_MessageDelta struct {
	MessageDelta *MessageDeltaEvent `protobuf:"bytes,14,opt,name=message_delta,json=messageDelta,proto3,oneof"`
}

type StreamEvent_MessageStop struct {
	MessageStop *MessageStopEvent `protobuf:"bytes,15,opt,name=message_stop,json=messageStop,proto3,oneof"`
}

type StreamEvent_Ping struct {
	Ping *PingEvent `protobuf:"bytes,16,opt,name=ping,proto3,oneof"`
}

func (*StreamEvent_MessageStart) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStart) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockDelta) isStreamEvent_Event() {}

func (*StreamEvent_ContentBlockStop) isStreamEvent_Event() {}

func (*StreamEvent_MessageDelta) isStreamEvent_Event() {}

func (*StreamEvent_MessageStop) isStreamEvent_Event() {}

func (*StreamEvent_Ping) isStreamEvent_Event() {}

// MessageStartEvent signals the beginning of a message stream
type MessageStartEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=a2a.v1.Role" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStartEvent) Reset() {
	*x = MessageStartEvent{}
	mi := &file_content_blocks_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStartEvent) ProtoMessage() {}

func (x *MessageStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStartEvent.ProtoReflect.Descriptor instead.
func (*MessageStartEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{8}
}

func (x *MessageStartEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *MessageStartEvent) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

// ContentBlockStartEvent signals the start of a content block
type ContentBlockStartEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of this block in the message's content block array
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The content block (with empty/initial content)
	ContentBlock  *ContentBlock `protobuf:"bytes,2,opt,name=content_block,json=contentBlock,proto3" json:"content_block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStartEvent) Reset() {
	*x = ContentBlockStartEvent{}
	mi := &file_content_blocks_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStartEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStartEvent) ProtoMessage() {}

func (x *ContentBlockStartEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStartEvent.ProtoReflect.Descriptor instead.
func (*ContentBlockStartEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{9}
}

func (x *ContentBlockStartEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ContentBlockStartEvent) GetContentBlock() *ContentBlock {
	if x != nil {
		return x.ContentBlock
	}
	return nil
}

// ContentBlockDeltaEvent provides incremental updates to a content block
type ContentBlockDeltaEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the block being updated
	Index int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	// The delta content
	//
	// Types that are valid to be assigned to Delta:
	//
	//	*ContentBlockDeltaEvent_TextDelta
	//	*ContentBlockDeltaEvent_ThinkingDelta
	//	*ContentBlockDeltaEvent_InputJsonDelta
	//	*ContentBlockDeltaEvent_SignatureDelta
	Delta         isContentBlockDeltaEvent_Delta `protobuf_oneof:"delta"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockDeltaEvent) Reset() {
	*x = ContentBlockDeltaEvent{}
	mi := &file_content_blocks_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockDeltaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockDeltaEvent) ProtoMessage() {}

func (x *ContentBlockDeltaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockDeltaEvent.ProtoReflect.Descriptor instead.
func (*ContentBlockDeltaEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{10}
}

func (x *ContentBlockDeltaEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ContentBlockDeltaEvent) GetDelta() isContentBlockDeltaEvent_Delta {
	if x != nil {
		return x.Delta
	}
	return nil
}

func (x *ContentBlockDeltaEvent) GetTextDelta() *TextDelta {
	if x != nil {
		if x, ok := x.Delta.(*ContentBlockDeltaEvent_TextDelta); ok {
			return x.TextDelta
		}
	}
	return nil
}

func (x *ContentBlockDeltaEvent) GetThinkingDelta() *ThinkingDelta {
	if x != nil {
		if x, ok := x.Delta.(*ContentBlockDeltaEvent_ThinkingDelta); ok {
			return x.ThinkingDelta
		}
	}
	return nil
}

func (x *ContentBlockDeltaEvent) GetInputJsonDelta() *InputJsonDelta {
	if x != nil {
		if x, ok := x.Delta.(*ContentBlockDeltaEvent_InputJsonDelta); ok {
			return x.InputJsonDelta
		}
	}
	return nil
}

func (x *ContentBlockDeltaEvent) GetSignatureDelta() *SignatureDelta {
	if x != nil {
		if x, ok := x.Delta.(*ContentBlockDeltaEvent_SignatureDelta); ok {
			return x.SignatureDelta
		}
	}
	return nil
}

type isContentBlockDeltaEvent_Delta interface {
	isContentBlockDeltaEvent_Delta()
}

type ContentBlockDeltaEvent_TextDelta struct {
	TextDelta *TextDelta `protobuf:"bytes,10,opt,name=text_delta,json=textDelta,proto3,oneof"`
}

type ContentBlockDeltaEvent_ThinkingDelta struct {
	ThinkingDelta *ThinkingDelta `protobuf:"bytes,11,opt,name=thinking_delta,json=thinkingDelta,proto3,oneof"`
}

type ContentBlockDeltaEvent_InputJsonDelta struct {
	InputJsonDelta *InputJsonDelta `protobuf:"bytes,12,opt,name=input_json_delta,json=inputJsonDelta,proto3,oneof"`
}

type ContentBlockDeltaEvent_SignatureDelta struct {
	SignatureDelta *SignatureDelta `protobuf:"bytes,13,opt,name=signature_delta,json=signatureDelta,proto3,oneof"`
}

func (*ContentBlockDeltaEvent_TextDelta) isContentBlockDeltaEvent_Delta() {}

func (*ContentBlockDeltaEvent_ThinkingDelta) isContentBlockDeltaEvent_Delta() {}

func (*ContentBlockDeltaEvent_InputJsonDelta) isContentBlockDeltaEvent_Delta() {}

func (*ContentBlockDeltaEvent_SignatureDelta) isContentBlockDeltaEvent_Delta() {}

// TextDelta provides incremental text content
type TextDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextDelta) Reset() {
	*x = TextDelta{}
	mi := &file_content_blocks_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextDelta) ProtoMessage() {}

func (x *TextDelta) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextDelta.ProtoReflect.Descriptor instead.
func (*TextDelta) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{11}
}

func (x *TextDelta) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// ThinkingDelta provides incremental thinking content
type ThinkingDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thinking      string                 `protobuf:"bytes,1,opt,name=thinking,proto3" json:"thinking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingDelta) Reset() {
	*x = ThinkingDelta{}
	mi := &file_content_blocks_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingDelta) ProtoMessage() {}

func (x *ThinkingDelta) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingDelta.ProtoReflect.Descriptor instead.
func (*ThinkingDelta) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{12}
}

func (x *ThinkingDelta) GetThinking() string {
	if x != nil {
		return x.Thinking
	}
	return ""
}

// InputJsonDelta provides incremental tool input (as partial JSON)
type InputJsonDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartialJson   string                 `protobuf:"bytes,1,opt,name=partial_json,json=partialJson,proto3" json:"partial_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputJsonDelta) Reset() {
	*x = InputJsonDelta{}
	mi := &file_content_blocks_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputJsonDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputJsonDelta) ProtoMessage() {}

func (x *InputJsonDelta) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputJsonDelta.ProtoReflect.Descriptor instead.
func (*InputJsonDelta) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{13}
}

func (x *InputJsonDelta) GetPartialJson() string {
	if x != nil {
		return x.PartialJson
	}
	return ""
}

// SignatureDelta provides signature content (sent before block stop)
type SignatureDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureDelta) Reset() {
	*x = SignatureDelta{}
	mi := &file_content_blocks_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureDelta) ProtoMessage() {}

func (x *SignatureDelta) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureDelta.ProtoReflect.Descriptor instead.
func (*SignatureDelta) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{14}
}

func (x *SignatureDelta) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

// ContentBlockStopEvent signals the completion of a content block
type ContentBlockStopEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Index of the completed block
	Index         int32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContentBlockStopEvent) Reset() {
	*x = ContentBlockStopEvent{}
	mi := &file_content_blocks_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContentBlockStopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContentBlockStopEvent) ProtoMessage() {}

func (x *ContentBlockStopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContentBlockStopEvent.ProtoReflect.Descriptor instead.
func (*ContentBlockStopEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{15}
}

func (x *ContentBlockStopEvent) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// MessageDeltaEvent provides message-level updates (e.g., token counts)
type MessageDeltaEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Cumulative token usage
	Usage         *TokenUsage `protobuf:"bytes,1,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageDeltaEvent) Reset() {
	*x = MessageDeltaEvent{}
	mi := &file_content_blocks_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageDeltaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageDeltaEvent) ProtoMessage() {}

func (x *MessageDeltaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageDeltaEvent.ProtoReflect.Descriptor instead.
func (*MessageDeltaEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{16}
}

func (x *MessageDeltaEvent) GetUsage() *TokenUsage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// TokenUsage tracks token consumption
type TokenUsage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InputTokens   int32                  `protobuf:"varint,1,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,2,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	TotalTokens   int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsage) Reset() {
	*x = TokenUsage{}
	mi := &file_content_blocks_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsage) ProtoMessage() {}

func (x *TokenUsage) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsage.ProtoReflect.Descriptor instead.
func (*TokenUsage) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{17}
}

func (x *TokenUsage) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsage) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

func (x *TokenUsage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// MessageStopEvent signals the end of a message stream
type MessageStopEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageStopEvent) Reset() {
	*x = MessageStopEvent{}
	mi := &file_content_blocks_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageStopEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageStopEvent) ProtoMessage() {}

func (x *MessageStopEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageStopEvent.ProtoReflect.Descriptor instead.
func (*MessageStopEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{18}
}

func (x *MessageStopEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

// PingEvent for keepalive during streaming
type PingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingEvent) Reset() {
	*x = PingEvent{}
	mi := &file_content_blocks_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEvent) ProtoMessage() {}

func (x *PingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_content_blocks_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEvent.ProtoReflect.Descriptor instead.
func (*PingEvent) Descriptor() ([]byte, []int) {
	return file_content_blocks_proto_rawDescGZIP(), []int{19}
}

func (x *PingEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_content_blocks_proto protoreflect.FileDescriptor

const file_content_blocks_proto_rawDesc = "" +
	"\n" +
	"\x14content_blocks.proto\x12\x11a2a.v1.extensions\x1a\x1cgoogle/protobuf/struct.proto\x1a\ta2a.proto\"\xde\x04\n" +
	"\fContentBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x127\n" +
	"\x04type\x18\x02 \x01(\x0e2#.a2a.v1.extensions.ContentBlockTypeR\x04type\x12=\n" +
	"\n" +
	"text_block\x18\n" +
	" \x01(\v2\x1c.a2a.v1.extensions.TextBlockH\x00R\ttextBlock\x12I\n" +
	"\x0ethinking_block\x18\v \x01(\v2 .a2a.v1.extensions.ThinkingBlockH\x00R\rthinkingBlock\x12J\n" +
	"\x0ftool_call_block\x18\f \x01(\v2 .a2a.v1.extensions.ToolCallBlockH\x00R\rtoolCallBlock\x12P\n" +
	"\x11tool_result_block\x18\r \x01(\v2\".a2a.v1.extensions.ToolResultBlockH\x00R\x0ftoolResultBlock\x12L\n" +
	"\x0freasoning_block\x18\x0e \x01(\v2!.a2a.v1.extensions.ReasoningBlockH\x00R\x0ereasoningBlock\x12I\n" +
	"\bmetadata\x18\x14 \x03(\v2-.a2a.v1.extensions.ContentBlock.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\a\n" +
	"\x05block\"\x1f\n" +
	"\tTextBlock\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"\x8a\x01\n" +
	"\rThinkingBlock\x12\x1a\n" +
	"\bthinking\x18\x01 \x01(\tR\bthinking\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12?\n" +
	"\bmetadata\x18\x03 \x01(\v2#.a2a.v1.extensions.ThinkingMetadataR\bmetadata\"\xc4\x02\n" +
	"\x10ThinkingMetadata\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vcollapsible\x18\x02 \x01(\bR\vcollapsible\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x1c\n" +
	"\tephemeral\x18\x04 \x01(\bR\tephemeral\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12S\n" +
	"\n" +
	"attributes\x18\a \x03(\v23.a2a.v1.extensions.ThinkingMetadata.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8d\x01\n" +
	"\x0eReasoningBlock\x12\x1c\n" +
	"\treasoning\x18\x01 \x01(\tR\treasoning\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\tR\tsignature\x12?\n" +
	"\bmetadata\x18\x03 \x01(\v2#.a2a.v1.extensions.ThinkingMetadataR\bmetadata\"I\n" +
	"\rToolCallBlock\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05input\x18\x03 \x01(\tR\x05input\"h\n" +
	"\x0fToolResultBlock\x12 \n" +
	"\ftool_call_id\x18\x01 \x01(\tR\n" +
	"toolCallId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x19\n" +
	"\bis_error\x18\x03 \x01(\bR\aisError\"\xfa\x04\n" +
	"\vStreamEvent\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".a2a.v1.extensions.StreamEventTypeR\x04type\x12K\n" +
	"\rmessage_start\x18\n" +
	" \x01(\v2$.a2a.v1.extensions.MessageStartEventH\x00R\fmessageStart\x12[\n" +
	"\x13content_block_start\x18\v \x01(\v2).a2a.v1.extensions.ContentBlockStartEventH\x00R\x11contentBlockStart\x12[\n" +
	"\x13content_block_delta\x18\f \x01(\v2).a2a.v1.extensions.ContentBlockDeltaEventH\x00R\x11contentBlockDelta\x12X\n" +
	"\x12content_block_stop\x18\r \x01(\v2(.a2a.v1.extensions.ContentBlockStopEventH\x00R\x10contentBlockStop\x12K\n" +
	"\rmessage_delta\x18\x0e \x01(\v2$.a2a.v1.extensions.MessageDeltaEventH\x00R\fmessageDelta\x12H\n" +
	"\fmessage_stop\x18\x0f \x01(\v2#.a2a.v1.extensions.MessageStopEventH\x00R\vmessageStop\x122\n" +
	"\x04ping\x18\x10 \x01(\v2\x1c.a2a.v1.extensions.PingEventH\x00R\x04pingB\a\n" +
	"\x05event\"T\n" +
	"\x11MessageStartEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12 \n" +
	"\x04role\x18\x02 \x01(\x0e2\f.a2a.v1.RoleR\x04role\"t\n" +
	"\x16ContentBlockStartEvent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12D\n" +
	"\rcontent_block\x18\x02 \x01(\v2\x1f.a2a.v1.extensions.ContentBlockR\fcontentBlock\"\xde\x02\n" +
	"\x16ContentBlockDeltaEvent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\x12=\n" +
	"\n" +
	"text_delta\x18\n" +
	" \x01(\v2\x1c.a2a.v1.extensions.TextDeltaH\x00R\ttextDelta\x12I\n" +
	"\x0ethinking_delta\x18\v \x01(\v2 .a2a.v1.extensions.ThinkingDeltaH\x00R\rthinkingDelta\x12M\n" +
	"\x10input_json_delta\x18\f \x01(\v2!.a2a.v1.extensions.InputJsonDeltaH\x00R\x0einputJsonDelta\x12L\n" +
	"\x0fsignature_delta\x18\r \x01(\v2!.a2a.v1.extensions.SignatureDeltaH\x00R\x0esignatureDeltaB\a\n" +
	"\x05delta\"\x1f\n" +
	"\tTextDelta\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"+\n" +
	"\rThinkingDelta\x12\x1a\n" +
	"\bthinking\x18\x01 \x01(\tR\bthinking\"3\n" +
	"\x0eInputJsonDelta\x12!\n" +
	"\fpartial_json\x18\x01 \x01(\tR\vpartialJson\".\n" +
	"\x0eSignatureDelta\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\"-\n" +
	"\x15ContentBlockStopEvent\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x05R\x05index\"H\n" +
	"\x11MessageDeltaEvent\x123\n" +
	"\x05usage\x18\x01 \x01(\v2\x1d.a2a.v1.extensions.TokenUsageR\x05usage\"w\n" +
	"\n" +
	"TokenUsage\x12!\n" +
	"\finput_tokens\x18\x01 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x02 \x01(\x05R\foutputTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"1\n" +
	"\x10MessageStopEvent\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\")\n" +
	"\tPingEvent\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp*\x80\x03\n" +
	"\x10ContentBlockType\x12\"\n" +
	"\x1eCONTENT_BLOCK_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONTENT_BLOCK_TYPE_TEXT\x10\x01\x12\x1f\n" +
	"\x1bCONTENT_BLOCK_TYPE_THINKING\x10\x02\x12 \n" +
	"\x1cCONTENT_BLOCK_TYPE_REASONING\x10\x03\x12 \n" +
	"\x1cCONTENT_BLOCK_TYPE_TOOL_CALL\x10\x04\x12\"\n" +
	"\x1eCONTENT_BLOCK_TYPE_TOOL_RESULT\x10\x05\x12!\n" +
	"\x1dCONTENT_BLOCK_TYPE_REFLECTION\x10\x06\x12\x1f\n" +
	"\x1bCONTENT_BLOCK_TYPE_PLANNING\x10\a\x12\x1f\n" +
	"\x1bCONTENT_BLOCK_TYPE_PROGRESS\x10\b\x12\x1c\n" +
	"\x18CONTENT_BLOCK_TYPE_DEBUG\x10\t\x12\x1f\n" +
	"\x1bCONTENT_BLOCK_TYPE_ANALYSIS\x10\n" +
	"*\xbe\x02\n" +
	"\x0fStreamEventType\x12!\n" +
	"\x1dSTREAM_EVENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSTREAM_EVENT_TYPE_MESSAGE_START\x10\x01\x12)\n" +
	"%STREAM_EVENT_TYPE_CONTENT_BLOCK_START\x10\x02\x12)\n" +
	"%STREAM_EVENT_TYPE_CONTENT_BLOCK_DELTA\x10\x03\x12(\n" +
	"$STREAM_EVENT_TYPE_CONTENT_BLOCK_STOP\x10\x04\x12#\n" +
	"\x1fSTREAM_EVENT_TYPE_MESSAGE_DELTA\x10\x05\x12\"\n" +
	"\x1eSTREAM_EVENT_TYPE_MESSAGE_STOP\x10\x06\x12\x1a\n" +
	"\x16STREAM_EVENT_TYPE_PING\x10\aBo\n" +
	"\x1ccom.google.a2a.v1.extensionsB\rContentBlocksP\x01Z*github.com/kadirpekel/hector/pkg/a2a/pb;pb\xaa\x02\x11A2a.V1.Extensionsb\x06proto3"

var (
	file_content_blocks_proto_rawDescOnce sync.Once
	file_content_blocks_proto_rawDescData []byte
)

func file_content_blocks_proto_rawDescGZIP() []byte {
	file_content_blocks_proto_rawDescOnce.Do(func() {
		file_content_blocks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_content_blocks_proto_rawDesc), len(file_content_blocks_proto_rawDesc)))
	})
	return file_content_blocks_proto_rawDescData
}

var file_content_blocks_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_content_blocks_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_content_blocks_proto_goTypes = []any{
	(ContentBlockType)(0),          // 0: a2a.v1.extensions.ContentBlockType
	(StreamEventType)(0),           // 1: a2a.v1.extensions.StreamEventType
	(*ContentBlock)(nil),           // 2: a2a.v1.extensions.ContentBlock
	(*TextBlock)(nil),              // 3: a2a.v1.extensions.TextBlock
	(*ThinkingBlock)(nil),          // 4: a2a.v1.extensions.ThinkingBlock
	(*ThinkingMetadata)(nil),       // 5: a2a.v1.extensions.ThinkingMetadata
	(*ReasoningBlock)(nil),         // 6: a2a.v1.extensions.ReasoningBlock
	(*ToolCallBlock)(nil),          // 7: a2a.v1.extensions.ToolCallBlock
	(*ToolResultBlock)(nil),        // 8: a2a.v1.extensions.ToolResultBlock
	(*StreamEvent)(nil),            // 9: a2a.v1.extensions.StreamEvent
	(*MessageStartEvent)(nil),      // 10: a2a.v1.extensions.MessageStartEvent
	(*ContentBlockStartEvent)(nil), // 11: a2a.v1.extensions.ContentBlockStartEvent
	(*ContentBlockDeltaEvent)(nil), // 12: a2a.v1.extensions.ContentBlockDeltaEvent
	(*TextDelta)(nil),              // 13: a2a.v1.extensions.TextDelta
	(*ThinkingDelta)(nil),          // 14: a2a.v1.extensions.ThinkingDelta
	(*InputJsonDelta)(nil),         // 15: a2a.v1.extensions.InputJsonDelta
	(*SignatureDelta)(nil),         // 16: a2a.v1.extensions.SignatureDelta
	(*ContentBlockStopEvent)(nil),  // 17: a2a.v1.extensions.ContentBlockStopEvent
	(*MessageDeltaEvent)(nil),      // 18: a2a.v1.extensions.MessageDeltaEvent
	(*TokenUsage)(nil),             // 19: a2a.v1.extensions.TokenUsage
	(*MessageStopEvent)(nil),       // 20: a2a.v1.extensions.MessageStopEvent
	(*PingEvent)(nil),              // 21: a2a.v1.extensions.PingEvent
	nil,                            // 22: a2a.v1.extensions.ContentBlock.MetadataEntry
	nil,                            // 23: a2a.v1.extensions.ThinkingMetadata.AttributesEntry
	(Role)(0),                      // 24: a2a.v1.Role
}
var file_content_blocks_proto_depIdxs = []int32{
	0,  // 0: a2a.v1.extensions.ContentBlock.type:type_name -> a2a.v1.extensions.ContentBlockType
	3,  // 1: a2a.v1.extensions.ContentBlock.text_block:type_name -> a2a.v1.extensions.TextBlock
	4,  // 2: a2a.v1.extensions.ContentBlock.thinking_block:type_name -> a2a.v1.extensions.ThinkingBlock
	7,  // 3: a2a.v1.extensions.ContentBlock.tool_call_block:type_name -> a2a.v1.extensions.ToolCallBlock
	8,  // 4: a2a.v1.extensions.ContentBlock.tool_result_block:type_name -> a2a.v1.extensions.ToolResultBlock
	6,  // 5: a2a.v1.extensions.ContentBlock.reasoning_block:type_name -> a2a.v1.extensions.ReasoningBlock
	22, // 6: a2a.v1.extensions.ContentBlock.metadata:type_name -> a2a.v1.extensions.ContentBlock.MetadataEntry
	5,  // 7: a2a.v1.extensions.ThinkingBlock.metadata:type_name -> a2a.v1.extensions.ThinkingMetadata
	23, // 8: a2a.v1.extensions.ThinkingMetadata.attributes:type_name -> a2a.v1.extensions.ThinkingMetadata.AttributesEntry
	5,  // 9: a2a.v1.extensions.ReasoningBlock.metadata:type_name -> a2a.v1.extensions.ThinkingMetadata
	1,  // 10: a2a.v1.extensions.StreamEvent.type:type_name -> a2a.v1.extensions.StreamEventType
	10, // 11: a2a.v1.extensions.StreamEvent.message_start:type_name -> a2a.v1.extensions.MessageStartEvent
	11, // 12: a2a.v1.extensions.StreamEvent.content_block_start:type_name -> a2a.v1.extensions.ContentBlockStartEvent
	12, // 13: a2a.v1.extensions.StreamEvent.content_block_delta:type_name -> a2a.v1.extensions.ContentBlockDeltaEvent
	17, // 14: a2a.v1.extensions.StreamEvent.content_block_stop:type_name -> a2a.v1.extensions.ContentBlockStopEvent
	18, // 15: a2a.v1.extensions.StreamEvent.message_delta:type_name -> a2a.v1.extensions.MessageDeltaEvent
	20, // 16: a2a.v1.extensions.StreamEvent.message_stop:type_name -> a2a.v1.extensions.MessageStopEvent
	21, // 17: a2a.v1.extensions.StreamEvent.ping:type_name -> a2a.v1.extensions.PingEvent
	24, // 18: a2a.v1.extensions.MessageStartEvent.role:type_name -> a2a.v1.Role
	2,  // 19: a2a.v1.extensions.ContentBlockStartEvent.content_block:type_name -> a2a.v1.extensions.ContentBlock
	13, // 20: a2a.v1.extensions.ContentBlockDeltaEvent.text_delta:type_name -> a2a.v1.extensions.TextDelta
	14, // 21: a2a.v1.extensions.ContentBlockDeltaEvent.thinking_delta:type_name -> a2a.v1.extensions.ThinkingDelta
	15, // 22: a2a.v1.extensions.ContentBlockDeltaEvent.input_json_delta:type_name -> a2a.v1.extensions.InputJsonDelta
	16, // 23: a2a.v1.extensions.ContentBlockDeltaEvent.signature_delta:type_name -> a2a.v1.extensions.SignatureDelta
	19, // 24: a2a.v1.extensions.MessageDeltaEvent.usage:type_name -> a2a.v1.extensions.TokenUsage
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_content_blocks_proto_init() }
func file_content_blocks_proto_init() {
	if File_content_blocks_proto != nil {
		return
	}
	file_a2a_proto_init()
	file_content_blocks_proto_msgTypes[0].OneofWrappers = []any{
		(*ContentBlock_TextBlock)(nil),
		(*ContentBlock_ThinkingBlock)(nil),
		(*ContentBlock_ToolCallBlock)(nil),
		(*ContentBlock_ToolResultBlock)(nil),
		(*ContentBlock_ReasoningBlock)(nil),
	}
	file_content_blocks_proto_msgTypes[7].OneofWrappers = []any{
		(*StreamEvent_MessageStart)(nil),
		(*StreamEvent_ContentBlockStart)(nil),
		(*StreamEvent_ContentBlockDelta)(nil),
		(*StreamEvent_ContentBlockStop)(nil),
		(*StreamEvent_MessageDelta)(nil),
		(*StreamEvent_MessageStop)(nil),
		(*StreamEvent_Ping)(nil),
	}
	file_content_blocks_proto_msgTypes[10].OneofWrappers = []any{
		(*ContentBlockDeltaEvent_TextDelta)(nil),
		(*ContentBlockDeltaEvent_ThinkingDelta)(nil),
		(*ContentBlockDeltaEvent_InputJsonDelta)(nil),
		(*ContentBlockDeltaEvent_SignatureDelta)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_content_blocks_proto_rawDesc), len(file_content_blocks_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_content_blocks_proto_goTypes,
		DependencyIndexes: file_content_blocks_proto_depIdxs,
		EnumInfos:         file_content_blocks_proto_enumTypes,
		MessageInfos:      file_content_blocks_proto_msgTypes,
	}.Build()
	File_content_blocks_proto = out.File
	file_content_blocks_proto_goTypes = nil
	file_content_blocks_proto_depIdxs = nil
}
