# Hector Documentation - GitHub Pages Configuration

# Site settings
title: "Hector Documentation"
description: "Pure A2A-Native Declarative AI Agent Platform - Complete Documentation"
url: "https://gohector.dev"
baseurl: ""
repository: "kadirpekel/hector"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Just the Docs theme configuration
color_scheme: nil  # Allows user to toggle between light/dark
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation structure for just-the-docs
nav_external_links:
  - title: "GitHub Repository"
    url: "https://github.com/kadirpekel/hector"
    hide_icon: false

# Footer content
footer_content: "Copyright &copy; 2025 Hector Team. Licensed under AGPL-3.0."

# Favicon and logo
logo: "hector-gopher.png"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Collections
collections:
  tutorials:
    output: true
    permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: "tutorials"
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - benchmarks/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - README_DEVELOPMENT.md

# SEO and social
author: "Hector Team"
twitter:
  username: hectorai
  card: summary_large_image

# GitHub Pages specific
github:
  repository_url: "https://github.com/kadirpekel/hector"
  repository_name: "hector"
  owner_name: "kadirpekel"
  
# Custom variables
hector:
  version: "1.0.0"
  repo_url: "https://github.com/kadirpekel/hector"
  docs_url: "https://gohector.dev"
  demo_url: "https://demo.gohector.dev"
  discord_url: "https://discord.gg/hector"
