agents:
  test_agent_supervisor:
    name: "Supervisor Test Agent (Anthropic)"
    description: "Test agent with supervisor strategy and goal extraction"
    llm: "anthropic-llm"
    reasoning:
      engine: "supervisor"
      max_iterations: 10
      enable_self_reflection: true
      enable_structured_reflection: true
      enable_completion_verification: true
      enable_goal_extraction: true
      enable_streaming: true
      show_debug_info: true
    visibility: public

llms:
  anthropic-llm:
    type: "anthropic"
    model: "claude-3-5-sonnet-20241022"
    api_key: "${ANTHROPIC_API_KEY}"
    temperature: 0.7
    max_tokens: 4096

server:
  port: 8080
  host: "0.0.0.0"

