# Supervisor with goal extraction
# Provider: OpenAI GPT-4
agents:
  supervisor_agent:
    name: "Supervisor Test Agent (OpenAI)"
    description: "Supervisor agent with goal extraction enabled"
    llm: "openai-llm"
    reasoning:
      engine: "supervisor"
      max_iterations: 10
      enable_self_reflection: true
      enable_structured_reflection: true
      enable_completion_verification: true
      enable_goal_extraction: true              # TEST: Goal extraction
      show_debug_info: true
      show_tool_execution: true
      enable_streaming: false
    visibility: public

llms:
  openai-llm:
    type: "openai"
    model: "gpt-4o"
    api_key: "${OPENAI_API_KEY}"
    temperature: 0.3
    max_tokens: 4096
    timeout: 60

server:
  port: 8080
  host: "0.0.0.0"

