name: CI

on:
  # Run CI on pull requests for testing before merge
  pull_request:
    branches: [ main ]
  # Run full CI only on release tags
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
    
    - name: Run make quality
      run: make quality
    
    - name: Generate coverage report
      run: go test -v -coverprofile=coverage.out ./...
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.out
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  build:
    runs-on: ubuntu-latest
    needs: quality
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.24.x
    
    - name: Build
      run: |
        go build -ldflags "-X 'github.com/kadirpekel/hector.BuildDate=$(date -u +%Y-%m-%dT%H:%M:%SZ)' -X 'github.com/kadirpekel/hector.GitCommit=$(git rev-parse --short HEAD)'" -o hector ./cmd/hector
    
    - name: Test binary
      run: ./hector version
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: hector-linux-amd64
        path: hector
